"""Writes `BurmeseLexiconSource.tsv` from the unified vocab + corpus counts.

The TSV format consumed by `LexiconBuilder` is:

    surface<TAB>frequency[<TAB>override_reading]

We drop the specials (`<s>`, `</s>`, `<unk>`) — they belong to the LM only.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from .vocab import CuratedEntry, SPECIALS, Vocab


def write_tsv(
    path: Path,
    vocab: Vocab,
    corpus_counts: Counter[str],
    curated: list[CuratedEntry],
    *,
    min_frequency: float = 1.0,
) -> int:
    """Emit the lexicon TSV. Returns the number of rows written.

    Frequency scaling: `LexiconBuilder` takes raw counts and log-normalises
    them to 0..1000. We therefore just hand it the raw corpus count (with a
    floor of `min_frequency` for curated entries that might not appear in
    the corpus at all).
    """
    overrides: dict[str, str] = {
        entry.surface: entry.override_reading
        for entry in curated
        if entry.override_reading
    }

    rows_written = 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# surface<TAB>frequency[<TAB>override_reading]\n")
        f.write("# Generated by corpus_builder — frequencies are Myanmar-C4 counts.\n")
        for word_id, surface in enumerate(vocab.surfaces):
            if surface in SPECIALS:
                continue
            count = corpus_counts.get(surface, 0)
            freq = max(float(count), min_frequency)
            override = overrides.get(surface)
            if override:
                f.write(f"{surface}\t{freq:.0f}\t{override}\n")
            else:
                f.write(f"{surface}\t{freq:.0f}\n")
            rows_written += 1
    return rows_written
