"""Writes `BurmeseLexiconSource.tsv` from the unified vocab + corpus counts.

The TSV format consumed by `LexiconBuilder` is:

    surface<TAB>frequency[<TAB>override_reading]

We drop the specials (`<s>`, `</s>`, `<unk>`) — they belong to the LM only.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path

from .segmenter import _has_non_myanmar_leading_scalar, _is_combining_mark_only
from .vocab import CuratedEntry, SPECIALS, Vocab


def _peer_key(override_reading: str | None) -> str | None:
    """Return the digit-stripped reading key used to bucket peers.

    The `2`/`3` suffixes on internal reading keys (e.g. `t2`, `aa2`) are
    variant selectors — surfaces sharing a digit-stripped reading are
    candidate-panel siblings from the user's perspective, which is the
    right grouping for peer-based smoothing.
    """
    if not override_reading:
        return None
    stripped = "".join(ch for ch in override_reading if not ch.isdigit())
    return stripped or None


def write_tsv(
    path: Path,
    vocab: Vocab,
    corpus_counts: Counter[str],
    curated: list[CuratedEntry],
    *,
    min_frequency: float = 1.0,
    curated_smoothing: float = 0.0,
) -> int:
    """Emit the lexicon TSV. Returns the number of rows written.

    Frequency scaling: `LexiconBuilder` takes raw counts and log-normalises
    them to 0..1000. We therefore just hand it the raw corpus count (with a
    floor of `min_frequency` for curated entries that might not appear in
    the corpus at all).

    ``curated_smoothing`` (κ) applies a Dirichlet-style additive prior to
    the counts of curated rows (those with an ``override_reading``), using
    the digit-stripped reading as the peer key::

        floor(entry) = count(entry) + κ · avg_peer_count_excluding_self

    Rationale: rare-but-canonical curated surfaces (reading overrides) get
    lifted relative to their candidate-panel siblings without the
    arbitrary hand-tuned frequency bumps the TSV used to accrete. Natural
    corpus rows (no override_reading) are left at ``max(count, min_frequency)``.
    When κ == 0 the behaviour matches the pre-smoothing pipeline exactly.

    Peer-group size < 2 or κ == 0: no smoothing; the row falls back to the
    standard ``max(count, min_frequency)`` floor.
    """
    overrides: dict[str, str] = {
        entry.surface: entry.override_reading
        for entry in curated
        if entry.override_reading
    }

    # Peer-average (excluding self) per (peer_key, surface). Only built
    # when smoothing is active — keeps the κ=0 path allocation-free.
    peer_avg_excl: dict[tuple[str, str], float] = {}
    if curated_smoothing > 0:
        groups: dict[str, list[tuple[str, int]]] = defaultdict(list)
        for entry in curated:
            pk = _peer_key(entry.override_reading)
            if pk is None:
                continue
            count = corpus_counts.get(entry.surface, 0)
            groups[pk].append((entry.surface, count))
        for pk, members in groups.items():
            if len(members) < 2:
                continue
            total = sum(c for _, c in members)
            n = len(members)
            for surface, count in members:
                peer_avg_excl[(pk, surface)] = (total - count) / (n - 1)

    smoothed_count = 0
    smoothed_floors: list[float] = []
    rows_written = 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# surface<TAB>frequency[<TAB>override_reading]\n")
        f.write("# Generated by corpus_builder — frequencies are Myanmar-C4 counts.\n")
        if curated_smoothing > 0:
            f.write(f"# Dirichlet smoothing for curated rows: κ={curated_smoothing}\n")
        for word_id, surface in enumerate(vocab.surfaces):
            if surface in SPECIALS:
                continue
            # Defensive assertion: if a polluted surface makes it this
            # far, the segmenter / vocab guards upstream have a hole.
            # Fail loud rather than bake noise into the next round-trip
            # (task 05).
            if _is_combining_mark_only(surface) or _has_non_myanmar_leading_scalar(surface):
                raise ValueError(
                    f"lexicon.write_tsv: refusing to write polluted "
                    f"surface {surface!r} (non-Myanmar leading scalar, "
                    f"BOM-bearing, digit+mark orphan, or combining-mark-only)"
                )
            count = corpus_counts.get(surface, 0)
            override = overrides.get(surface)
            freq: float
            if override and curated_smoothing > 0:
                pk = _peer_key(override)
                avg_peers = peer_avg_excl.get((pk, surface)) if pk else None
                if avg_peers is not None:
                    freq = float(count) + curated_smoothing * avg_peers
                    smoothed_count += 1
                    smoothed_floors.append(freq)
                else:
                    freq = max(float(count), min_frequency)
            else:
                freq = max(float(count), min_frequency)
            if override:
                f.write(f"{surface}\t{freq:.0f}\t{override}\n")
            else:
                f.write(f"{surface}\t{freq:.0f}\n")
            rows_written += 1

    if curated_smoothing > 0 and smoothed_count:
        smoothed_floors.sort()
        mid = smoothed_floors[len(smoothed_floors) // 2]
        print(
            f"lexicon: Dirichlet-smoothed {smoothed_count} curated rows "
            f"(κ={curated_smoothing}, min={smoothed_floors[0]:.0f}, "
            f"median={mid:.0f}, max={smoothed_floors[-1]:.0f})"
        )
    return rows_written
