import Foundation

/// Tunable knobs for the ranking comparators.
///
/// `alpha` is the weight on the LM log-prob in the composite score
/// `log(rank_score) + α · lmLogProb` used by both grammar and lexicon
/// comparators. 0.4 is the midpoint of the 0.3–0.5 range suggested by
/// prior IME tuning literature; lower α biases toward parser/lexicon
/// frequency, higher α biases toward the LM.
public struct RankingTuning: Sendable {
    public let alpha: Double

    public init(alpha: Double = 0.4) {
        self.alpha = alpha
    }

    public static let `default` = RankingTuning()
}

/// The main composition engine for the Burmese IME.
///
/// Manages the composition buffer, generates candidates from grammar parsing
/// and lexicon lookup, and handles commit/cancel operations.
///
/// Ranking order: grammar legality > alias cost > LM log-prob > parser score
/// > lexicon frequency. The LM replaces the earlier hand-tuned bigram
/// boost — see `Packages/BurmeseIMECore/Sources/BurmeseIMECore/LanguageModel/FORMAT.md`.
///
/// The implementation is split across topic-focused extension files under
/// `Engine/`:
///
/// - `BurmeseEngine+Ranking.swift` — comparators, composite score, ya-pin
///   / alias promotion, LM-margin pruning.
/// - `BurmeseEngine+FrozenPrefix.swift` — prefix / LM-score caching,
///   syllable-safe split finding.
/// - `BurmeseEngine+Punctuation.swift` — mapped-punctuation handling,
///   literal-head splitting, creaky-tone detection.
/// - `BurmeseEngine+MidBufferDigits.swift` — mid-buffer digit extraction
///   / splicing, tail letter-run composition, digit conversion.
/// - `BurmeseEngine+Normalization.swift` — parser-input normalization,
///   acceptable-parse predicates, stack inference, ya-pin/ya-yit
///   normalization, ZWSP handling.
/// - `BurmeseEngine+Sanitizers.swift` — aa-shape correction, orphan
///   ZWNJ drops, Pali/bare-vowel overrides, polluted-surface filter.
public final class BurmeseEngine: @unchecked Sendable {

    /// Number of N-best parses requested from `SyllableParser` per keystroke.
    /// This is the pool the LM re-ranks; candidates ranked beyond this by the
    /// parser's own score never reach the LM, so it must be large enough to
    /// include plausible medial/onset alternates. The parser's internal beam
    /// scales to `max(budget × 16, 64)`, so a budget of 64 keeps the beam
    /// ≈1024 — still comfortably sub-millisecond on an M-series Mac.
    private static let grammarCandidateBudget = 32

    /// Expanded N-best budget for readings where `h` participates in a
    /// high-ambiguity cluster: it may be an aspirated onset marker, a
    /// ha-medial, or part of a following consonant run. A narrow DP beam
    /// drops LM-favored siblings such as `than3hly2in` and `ahaakhyain`
    /// before the ranker can compare them, while ordinary buffers should
    /// keep the smaller hot-path budget.
    private static let expandedGrammarCandidateBudget = 48

    /// Budget for the second `parseCandidates` call that
    /// `inferImplicitStackMarkers` makes when an implicit stack site is
    /// detected. The primary parse already enumerates every unstacked
    /// interpretation, so this pass only needs to surface the stacked
    /// top pick plus a small set of medial alternates. A narrower beam
    /// here is the single biggest lever on the `long` / `incremental`
    /// regression that task 09 introduced — the second parse is what
    /// ~doubled per-keystroke cost on kinzi-bearing buffers. The merge
    /// only needs the top stacked pick plus its nearest alternate.
    private static let stackInferenceBudget = 2

    /// Maximum natural-log-probability gap a candidate may trail the best
    /// LM-ranked candidate before being dropped. 8 ≈ factor ~3000×; well
    /// below that and the candidate is almost certainly nonsense noise
    /// generated by the parser. Keeps the panel to plausible picks only.
    /// Used as the fallback when no `IMESettings` instance is supplied.
    private static let lmPruneMarginDefault: Double = 8.0

    /// LM log-prob gap above which the LM signal dominates over the
    /// composite `log(rank_score) + α·lm` in the grammar comparator. At
    /// 1 nat (≈ factor 2.7× in probability), the LM is differentiating
    /// candidates strongly enough that a lexicon-absorbed score shouldn't
    /// be able to override it — otherwise ya-pin surfaces (LM-preferred
    /// but lexicon-penalty-suppressed) lose to ya-yit siblings that get
    /// a big absorption boost. For gaps under this threshold, composite
    /// falls through and lexicon-anchored surfaces can tip close races
    /// toward the lexicon-validated form (e.g. `an` → `အံ`).
    internal static let lmDominanceThreshold: Double = 1.0

    internal let parser: SyllableParser
    private let candidateStore: any CandidateStore
    /// Word-lattice / segmentation decoder layered on top of the parser
    /// + lexicon. Initialised eagerly because it captures the LM and
    /// store references that are passed in at engine-init time anyway.
    /// Kept as an implicit-`let` rather than `Optional` so callers can
    /// always invoke it; an empty store / null LM degrade it into a
    /// pass-through that returns `[]` quickly.
    private let latticeDecoder: WordLatticeDecoder
    private let historyStore: any UserHistoryStore
    internal let languageModel: any LanguageModel

    /// Sliding-window threshold for the full N-best parse. When the
    /// normalized buffer exceeds this, everything before the trailing
    /// window is rendered once via a cheap single-best parse and cached;
    /// only the tail is re-parsed on each keystroke. The window covers
    /// `maxOnsetLen + maxVowelLen` plus a safety margin so no rule can
    /// span the prefix/tail boundary.
    ///
    /// Boundary guards reject known cross-boundary contexts (`a...`
    /// connectors and `...in<C>` coda sites) rather than widening this
    /// window, which keeps the incremental benchmark within its p95/p99
    /// budget.
    private let compositionWindowSize: Int

    /// Small LRU (most-recent-first). Survives backspace-then-retype without
    /// re-parsing the frozen prefix. Capacity is deliberately tiny — each
    /// entry is one parse plus its branches (typically K=1), and linear scan
    /// at this size is cheaper than dictionary overhead.
    internal var prefixCache: [FrozenPrefixCache] = []
    internal let cacheLock = NSLock()

    private struct StackInferenceParseCache {
        let input: String
        let isFullBuffer: Bool
        let parses: [SyllableParse]
    }

    private var stackInferenceParseCache: [StackInferenceParseCache] = []
    private static let maxStackInferenceParseCache = 16

    /// History of anchors (checkpoints) ordered by `normalized.count`.
    /// When the latest/deepest anchor's tail can't parse standalone
    /// (e.g. a single "a" or ":"), we fall back to an earlier checkpoint
    /// whose tail is long enough to parse. This keeps the rendered
    /// prefix stable even across intermediate strokes where the tail
    /// alone is ambiguous.
    private var anchorHistory: [PrefixAnchor] = []
    private static let maxAnchorHistory = 32

    /// Last alias-normalized lookup key produced by `update`. Captured under
    /// `cacheLock` so `recordSelection` can write the same key the lexicon
    /// and history stores would have seen on lookup — keeping write/read
    /// symmetric without plumbing the key through `CompositionState`.
    private var lastHistoryKey: String = ""

    /// Upper bound on the active-tail length before the frozen prefix is
    /// extended forward. Keeping this larger than `compositionWindowSize`
    /// means an already-chosen prefix stays stable for many keystrokes —
    /// the committed portion the user sees doesn't shift as they type.
    /// Only when the tail reaches this size do we advance the split point.
    private static let maxActiveTailSize = 40

    /// Roman-input length past which a previously-rendered top candidate
    /// is treated as "committed" and will not be re-parsed on subsequent
    /// keystrokes. Below this, the engine always performs a fresh full-
    /// buffer parse so that early ambiguous picks (e.g. `k`, `kw`, `kwy`
    /// before medials can be disambiguated) can be overwritten by a
    /// clearly better interpretation once enough characters exist. At or
    /// above this length, the LM had real evidence when selecting the
    /// anchor, so we lock it to prevent the committed portion from
    /// silently drifting under the user.
    /// Fallback used when no `IMESettings` instance is supplied.
    private static let anchorCommitThresholdDefault = 8

    /// Minimum normalised-reading length before the lattice decoder
    /// runs. Below this, the parser + whole-buffer lexicon path is
    /// already optimal and lattice injection only invites rare
    /// lexicon surfaces (tone-variant `ကျွန်တော့်` vs `ကျွန်တော်`
    /// being the canonical example, winning the coda-only
    /// single-scalar LM tiebreak by a narrow margin) to outrank clean
    /// parser output. 12 is just above the single-word-plus-particle
    /// ceiling (`kwyantaw` = 8 chars, `kwyantawka` = 10) and well
    /// below where multi-word debt kicks in (~15+ chars).
    private static let latticeMinReadingLen = 12

    /// Maximum log-prob gap a lattice candidate can trail the
    /// lattice top before being dropped at engine-injection time.
    /// 3 nats ≈ factor 20×; anything weaker than that is a tail
    /// variant (retroflex `ဌ`, punctuation artefact) that the
    /// anchor history would promote on subsequent keystrokes if we
    /// kept it in the panel at an intermediate buffer length.
    private static let latticeLmInjectionMargin: Double = 3.0

    /// Page size for candidate display. Fallback used when no `IMESettings`
    /// instance is supplied.
    public static let candidatePageSizeDefault = 9

    private let settings: IMESettings?
    internal let tuning: RankingTuning

    /// Live-read wrapper. Falls back to the static default when no settings
    /// instance is wired; otherwise reflects the shared UserDefaults value,
    /// so the IMK extension sees changes without an engine rebuild.
    public var candidatePageSize: Int {
        settings?.candidatePageSize ?? Self.candidatePageSizeDefault
    }
    internal var lmPruneMargin: Double {
        settings?.lmPruneMargin ?? Self.lmPruneMarginDefault
    }
    private var anchorCommitThreshold: Int {
        settings?.anchorCommitThreshold ?? Self.anchorCommitThresholdDefault
    }
    internal var burmesePunctuationEnabled: Bool {
        settings?.burmesePunctuationEnabled ?? false
    }

    public init(
        candidateStore: any CandidateStore = EmptyCandidateStore(),
        historyStore: any UserHistoryStore = EmptyUserHistoryStore(),
        languageModel: any LanguageModel = NullLanguageModel(),
        settings: IMESettings? = nil,
        tuning: RankingTuning = .default
    ) {
        let useClusterAliases = settings?.clusterAliasesEnabled ?? true
        let parser = SyllableParser(useClusterAliases: useClusterAliases)
        self.parser = parser
        self.candidateStore = candidateStore
        self.historyStore = historyStore
        self.languageModel = languageModel
        self.latticeDecoder = WordLatticeDecoder(
            parser: parser,
            candidateStore: candidateStore,
            languageModel: languageModel,
            tuning: tuning
        )
        self.settings = settings
        self.tuning = tuning
        // Active-tail size in Roman chars. Once the buffer exceeds this,
        // everything before a syllable-safe boundary is parsed once and
        // cached (the "frozen prefix"); subsequent keystrokes only re-parse
        // the trailing window. A naïve character-count split was the source
        // of the earlier "garbage variants past the threshold" bug — the
        // split now snaps back to the nearest position where the prefix
        // parses fully legally on its own, so it never cuts mid-syllable.
        self.compositionWindowSize = 18
    }

    private static func grammarCandidateBudget(for normalizedInput: String) -> Int {
        if normalizedInput.contains("khy") || normalizedInput.contains("hly") {
            return expandedGrammarCandidateBudget
        }
        return grammarCandidateBudget
    }

    /// Update the composition state based on the current buffer and context.
    /// Called on every keystroke that modifies the buffer.
    public func update(buffer: String, context: [String]) -> CompositionState {
        guard !buffer.isEmpty else {
            cacheLock.lock()
            anchorHistory.removeAll()
            stackInferenceParseCache.removeAll()
            lastHistoryKey = ""
            cacheLock.unlock()
            return CompositionState(committedContext: context)
        }
        let displayBuffer = buffer.lowercased()
        // Task 10: Peel mid-buffer ASCII digits (letter-digit-letter) off
        // the buffer before the rest of the pipeline runs, then splice
        // them back into each candidate surface at the scalar position
        // corresponding to the letters typed before the digit. Without
        // this, `splitComposablePrefix` breaks at the digit and the
        // post-digit letters fall back to ZWNJ + dependent-mark orphans.
        let (midCleanedBuffer, midInsertions) =
            Self.extractMidBufferDigits(displayBuffer)
        if !midInsertions.isEmpty {
            var state = update(buffer: midCleanedBuffer, context: context)
            state.rawBuffer = displayBuffer
            state.candidates = spliceMidBufferDigits(
                into: state.candidates,
                cleaned: midCleanedBuffer,
                insertions: midInsertions
            )
            return state
        }
        // Composing punctuation (`.`, `:`, `*`, `'`) can appear inside
        // the roman run even when it cannot be consumed by a vowel or
        // connector rule. Split those literal runs before the parser can
        // skip them and silently erase what the user typed.
        if let split = splitAtLastEmbeddedComposingPunct(displayBuffer) {
            var state = update(buffer: split.activeBuffer, context: context)
            state.rawBuffer = displayBuffer
            if state.candidates.isEmpty {
                state.candidates = [Candidate(
                    surface: split.renderedPrefix + split.activeBuffer,
                    reading: displayBuffer,
                    source: .grammar,
                    score: 0
                )]
            } else {
                state.candidates = state.candidates.map { cand in
                    Candidate(
                        surface: split.renderedPrefix + cand.surface,
                        reading: cand.reading,
                        source: cand.source,
                        score: cand.score
                    )
                }
            }
            return state
        }
        // If punct mapping is on and the buffer contains a mapped-punct
        // char that is NOT just at the very tail, everything up to and
        // including the *last* such punct becomes a frozen rendering
        // (each composable run resolved via single-best parse, punct
        // chars replaced with their Myanmar equivalents). We then recurse
        // on the active suffix so the current word still gets N-best
        // candidates, and prepend the frozen prefix to every surface.
        if burmesePunctuationEnabled,
           let split = splitAtLastEmbeddedMappedPunct(displayBuffer) {
            var state = update(buffer: split.activeBuffer, context: context)
            state.rawBuffer = displayBuffer
            if state.candidates.isEmpty {
                // Active portion produced nothing parseable; surface the
                // frozen prefix + raw active so the user still sees the
                // settled portion and doesn't lose their composition.
                state.candidates = [Candidate(
                    surface: split.renderedPrefix + split.activeBuffer,
                    reading: displayBuffer,
                    source: .grammar,
                    score: 0
                )]
            } else {
                state.candidates = state.candidates.map { cand in
                    Candidate(
                        surface: split.renderedPrefix + cand.surface,
                        reading: cand.reading,
                        source: cand.source,
                        score: cand.score
                    )
                }
            }
            return state
        }
        // Peel a leading literal head (punctuation, brackets, quotes, …)
        // before digits / composable extraction. Without this, a buffer
        // starting with e.g. `.` or `(` collapses the composable prefix to
        // empty and returns no candidates even though `aung` / `thar`
        // after the literal are perfectly parseable.
        let (leadingLiteral, postLeadingLiteralBuffer) =
            Self.splitLeadingLiteral(displayBuffer)
        // Strip leading ASCII digits — they convert directly to Myanmar
        // digits and are prepended to candidate surfaces after the
        // composable portion is parsed.
        let (digitPrefix, postDigitBuffer) = Self.splitLeadingDigits(postLeadingLiteralBuffer)
        // Candidates are generated only from the leading run of composing
        // characters. Anything after the first non-composing character
        // (punctuation, whitespace, etc.) is held aside and emitted verbatim
        // on commit — this lets the user freely mix Burmese-convertible text
        // with literal content without the IME swallowing either.
        let (rawComposable, rawLiteralTail) = splitComposablePrefix(postDigitBuffer)
        // `.` is in `Romanization.composingCharacters` for abbreviation
        // handling, so trailing punctuation lands in the composable portion
        // rather than the literal tail. When punctuation mapping is on,
        // peel those trailing mapped chars off so the parser doesn't try
        // to consume them — they rejoin the tail below and get substituted
        // with their Myanmar equivalent when the surface is assembled.
        let composable: String
        let literalTail: String
        if burmesePunctuationEnabled {
            let (kept, peeled) = stripTrailingMappablePunctuation(rawComposable)
            composable = kept
            literalTail = peeled + rawLiteralTail
        } else {
            composable = rawComposable
            literalTail = rawLiteralTail
        }
        let initialNormalized = Self.normalizeForParser(composable)
        guard !initialNormalized.isEmpty else {
            // No composable text: if digits or literal text are present,
            // offer Burmese and Arabic digit candidates directly.
            let rawFullLiteral = leadingLiteral + digitPrefix + literalTail
            let mappedTail = burmesePunctuationEnabled
                ? Self.mapPunctuation(literalTail)
                : literalTail
            let fullLiteral = leadingLiteral + digitPrefix + mappedTail
            if Self.containsDigit(fullLiteral) {
                let burmese = leadingLiteral
                    + Self.arabicToBurmeseDigits(digitPrefix + mappedTail)
                var candidates = [Candidate(
                    surface: burmese,
                    reading: rawFullLiteral,
                    source: .grammar,
                    score: 0
                )]
                // Measure-word expansions apply only when the buffer is pure
                // ASCII digits (no tail content at all). Cap to 2 suffixes per
                // buffer so the plain-digit candidate stays the default pick.
                if settings?.numberMeasureWordsEnabled == true,
                   literalTail.isEmpty,
                   leadingLiteral.isEmpty,
                   !digitPrefix.isEmpty {
                    for entry in NumberMeasureWords.shared.candidates(
                        forDigits: digitPrefix, limit: 2
                    ) {
                        candidates.append(Candidate(
                            surface: "\(burmese) \(entry.measureWord)",
                            reading: rawFullLiteral,
                            source: .grammar,
                            score: 0
                        ))
                    }
                }
                if burmese != rawFullLiteral {
                    candidates.append(Candidate(
                        surface: rawFullLiteral,
                        reading: rawFullLiteral,
                        source: .grammar,
                        score: 0
                    ))
                }
                return CompositionState(
                    rawBuffer: displayBuffer,
                    selectedCandidateIndex: 0,
                    candidates: candidates,
                    committedContext: context
                )
            }
            return CompositionState(
                rawBuffer: displayBuffer,
                selectedCandidateIndex: 0,
                candidates: [],
                committedContext: context
            )
        }

        // Shrink from the right until the parser produces a fully legal
        // parse that doesn't begin with a standalone tall-aa vowel (ar2,
        // aw2, out2, aung2). The dropped suffix joins `literalTail`, so
        // "min:123" emits မင်း + "123" and "ar2" emits ာ + "2" — the
        // tall-aa variant remains reachable only when a descender onset is
        // actually present in the buffer.
        //
        // The probe always runs on the full normalized buffer: probing
        // only a trailing slice would start mid-syllable for long inputs
        // and reject valid letters that parse fine in full context.
        //
        // `parseLongestAcceptablePrefix` collapses the per-length loop
        // into a single DP pass + backward walk of its buckets. On garbage
        // / keyboard-bashing input this turns O(n) full parses into O(1).
        let (acceptableLen, _) = parser.parseLongestAcceptablePrefix(
            initialNormalized,
            maxResults: 1,
            acceptable: Self.isAcceptableParse
        )
        let initialChars = Array(initialNormalized)
        let normalized = String(initialChars.prefix(acceptableLen))
        let droppedTail = String(initialChars.suffix(initialChars.count - acceptableLen))

        guard !normalized.isEmpty else {
            return CompositionState(
                rawBuffer: displayBuffer,
                selectedCandidateIndex: 0,
                candidates: [],
                committedContext: context
            )
        }

        let rawEffectiveTail = droppedTail + literalTail
        // Punctuation auto-mapping substitutes Myanmar ။/၊ inside the tail
        // so the trailing char appears as part of each candidate surface
        // instead of forcing an early commit. Mapping touches only the
        // exact five ASCII punctuation chars — letters the parser dropped
        // into `droppedTail` pass through unchanged.
        let mappedEffectiveTail = burmesePunctuationEnabled
            ? Self.mapPunctuation(rawEffectiveTail)
            : rawEffectiveTail
        // When the right-shrink probe drops composing characters, re-run
        // the tail through the single-best fallback composer before it is
        // concatenated onto every surface. Literal tails that started after
        // a non-composing boundary still pass through unchanged.
        let effectiveTail: String
        let droppedTailHasComposingChars = droppedTail.contains {
            Romanization.composingCharacters.contains($0)
        }
        let droppedTailHasComposingPunctuation = droppedTail.contains {
            $0 == "+" || $0 == "*" || $0 == "'" || $0 == ":" || $0 == "."
        }
        let droppedTailHasAsciiLetters = droppedTail.unicodeScalars.contains {
            $0.value >= 0x61 && $0.value <= 0x7A
        }
        let shouldComposeDroppedTail = !droppedTail.isEmpty
            && droppedTailHasComposingChars
            && (droppedTail.count <= 6 || droppedTailHasComposingPunctuation)
        if tailStartsWithDigit(literalTail, dropped: droppedTail)
            || shouldComposeDroppedTail {
            effectiveTail = composeLetterRunsInTail(mappedEffectiveTail)
        } else {
            effectiveTail = mappedEffectiveTail
        }

        // Prefix-stability anchor: when the new buffer extends a
        // previously-rendered one *and* that anchor is mature enough
        // (`anchor.normalized.count >= anchorCommitThreshold`), reuse
        // the anchor surface verbatim and only re-parse the tail. Mature
        // anchors are treated as committed so the already-visible
        // rendering cannot drift. Below the threshold the anchor is
        // tentative — we perform a fresh full-buffer parse instead, so
        // early ambiguous picks get overwritten once evidence accrues.
        cacheLock.lock()
        let historySnapshot = anchorHistory
        cacheLock.unlock()
        // Walk the history deepest → shallowest and pick the first anchor
        // whose (a) normalized is a strict prefix of the current buffer,
        // (b) is long enough to count as committed, and (c) whose tail
        // parses on its own. A mature anchor whose tail cannot parse
        // (e.g. single trailing "a" or ":") would otherwise zero out the
        // candidate panel or force a full-buffer fallback that drifts;
        // stepping back to a shallower checkpoint gives us a parseable
        // tail while still preserving all prior committed text.
        // Minimum tail length for anchor-based windowing. A very short
        // tail (e.g. 1-2 chars) always "parses" as a bare consonant, but
        // that greedily locks in the anchor boundary and prevents multi-
        // character onsets (like "th" → သ) from forming across it. The
        // tail must be long enough for the parser to see the full onset +
        // vowel at the boundary; `maxOnsetLen` is the safe minimum.
        let minAnchorTailLen = parser.maxOnsetLen
        let priorAnchor: PrefixAnchor? = {
            guard normalized.count > compositionWindowSize else { return nil }
            let normalizedCharsForAnchors = Array(normalized)
            for anchor in historySnapshot.reversed() {
                guard !anchor.normalized.isEmpty,
                      normalized.hasPrefix(anchor.normalized),
                      normalized.count > anchor.normalized.count,
                      anchor.normalized.count >= anchorCommitThreshold,
                      !Self.isUnsafeFrozenSplit(
                          chars: normalizedCharsForAnchors,
                          split: anchor.normalized.count
                      )
                else { continue }
                let tail = String(normalized.suffix(normalized.count - anchor.normalized.count))
                guard tail.count >= minAnchorTailLen else { continue }
                let probe = parser.parseCandidates(tail, maxResults: 1)
                if probe.contains(where: { Self.isAcceptableParse($0) }) {
                    return anchor
                }
            }
            return nil
        }()
        // Suppress anchor-windowing when the full normalized buffer has an
        // exact-alias lexicon entry: a curated multi-word lexicon hit like
        // "မင်္ဂလာပါ" deserves to win over a synthesized prefix + tail
        // rendering. Anchor-windowing is still correct for novel inputs
        // where no full-buffer lexicon entry exists (the kwyantawkahtamin
        // case), because there the lookup is empty and this guard is false.
        let preAliasPrefix = Romanization.aliasReading(normalized)
        let preComposeKey = Romanization.composeLookupKey(normalized)
        let hasExactLexiconMatch: Bool = {
            let hits = candidateStore.lookup(prefix: preAliasPrefix, previousSurface: context.last)
            return hits.contains {
                Romanization.aliasReading($0.reading) == preAliasPrefix
                    || Romanization.composeLookupKey($0.reading) == preComposeKey
            }
        }()
        // Only use anchor-based parse splitting for long buffers where the
        // sliding window is needed. For short buffers (below compositionWindowSize),
        // always do a full-buffer parse so that syllable boundaries can be
        // freely revised as new characters arrive. Without this gate, the anchor
        // greedily commits boundaries that later keystrokes should change —
        // e.g. "la" + "r" staying as လ+ရ instead of becoming လာ (l + ar vowel),
        // or "ka" + "h" staying as က+ဟ instead of becoming က+ထ (ka + ht onset).
        let anchorApplies = priorAnchor != nil
            && !hasExactLexiconMatch
            && normalized.count > compositionWindowSize

        let prefixBranches: [FrozenPrefixBranch]
        let parseInput: String
        let windowed: Bool
        var lmCache: [LMScoreKey: Double] = [:]
        if anchorApplies, let anchor = priorAnchor {
            let anchorLM = scoreSurfaceCached(anchor.surface, context: context, cache: &lmCache)
            prefixBranches = [FrozenPrefixBranch(
                output: anchor.surface,
                reading: anchor.reading,
                lmScore: anchorLM,
                contextWords: context + [anchor.surface]
            )]
            parseInput = String(normalized.suffix(normalized.count - anchor.normalized.count))
            windowed = true
        } else if normalized.count > compositionWindowSize {
            // Prefer reusing a previously chosen frozen prefix so the
            // "committed" portion the user sees doesn't shift as they
            // type. The cached prefix is reused verbatim when it is
            // still a prefix of the current buffer and the remaining
            // tail hasn't grown past `maxActiveTailSize`. Only when the
            // tail exceeds that budget do we extend the split forward —
            // the new split is constrained to land at or after the
            // cached endpoint, so the committed portion only grows.
            let cachedLen = stableCachedPrefixLength(for: normalized)
            let normalizedChars = Array(normalized)
            let cachedIsUnsafe = cachedLen.map {
                Self.isUnsafeFrozenSplit(chars: normalizedChars, split: $0)
            } ?? false
            let split: Int
            if let cached = cachedLen,
               !cachedIsUnsafe,
               normalized.count - cached <= Self.maxActiveTailSize {
                split = cached
            } else {
                let splitLowerBound = max(cachedLen ?? 0, anchorCommitThreshold)
                split = Self.findSyllableSafeSplit(
                    in: normalized,
                    parser: parser,
                    targetTail: compositionWindowSize,
                    lowerBound: splitLowerBound
                )
            }
            let frozenPrefix = String(normalized.prefix(split))
            let activeTail = String(normalized.suffix(normalized.count - split))
            prefixBranches = renderFrozenPrefixBranches(frozenPrefix, baseContext: context, lmCache: &lmCache)
            parseInput = activeTail
            windowed = true
        } else {
            prefixBranches = []
            parseInput = normalized
            windowed = false
        }

        // When windowed, the tail-only input occasionally can't parse as
        // a standalone syllable (e.g. "ka" has no onset-less "a" rule in
        // this romanization). Falling through to an empty candidate pool
        // would blank the panel mid-word. Detect that case and retry
        // with the full normalized buffer so the user still sees
        // candidates — we trade a per-keystroke re-parse of the prefix
        // for continuity of the panel.
        var effectiveParseInput = parseInput
        var effectivePrefixBranches = prefixBranches
        var effectiveWindowed = windowed
        var grammarParses = parser.parseCandidates(
            effectiveParseInput,
            maxResults: Self.grammarCandidateBudget(for: effectiveParseInput),
            isFullBuffer: !effectiveWindowed
        )
        grammarParses.removeAll { Self.hasInterleavedLatin($0.output) }
        // Parser-level orphan promotion (task 01): generate implicit-အ
        // siblings for parses whose surface has an unanchored mark. The
        // leading-ZWNJ case swaps the ZWNJ for အ; the mid-surface case
        // inserts အ before every interior orphan
        // (`<...>103A 102D<...>` and friends). Both can coexist on the
        // same parent (`aungain` surfaces as ZWNJ + ...103A 102D...), so
        // run the mid-surface pass on the ZWNJ-promoted sibling too.
        // `sanitizeMalformedMyanmarMarks` drops the original orphan once
        // a legal sibling survives.
        let originalGrammarParseCount = grammarParses.count
        for i in 0..<originalGrammarParseCount {
            let parent = grammarParses[i]
            let zwnjPromoted = Self.promoteOrphanZwnjToImplicitA(parent)
            if let zwnjPromoted {
                grammarParses.append(zwnjPromoted)
            }
            if let promoted = Self.promoteOrphanInternalMarks(parent) {
                grammarParses.append(promoted)
            }
            if let zwnjPromoted,
               let promoted = Self.promoteOrphanInternalMarks(zwnjPromoted) {
                grammarParses.append(promoted)
            }
        }
        // Stack inference (tasks 09/05): when the buffer carries no
        // explicit `+` but has an orthographic kinzi / Pali virama-stack
        // site (`<V><coda><C>`), re-parse with the inferred `+` injected
        // and merge the resulting parses so the stacked surface enters the
        // ranking pool alongside the unstacked one. The inference pass uses
        // liberal stack validation; regular parsing remains strict.
        //
        // Each injected `+` materialises as a DP vowelOnly transition
        // that bumps `syllableCount` by 1 even when the site resolves
        // to a stack — so the stacked parse would lose the
        // `syllableCount` tiebreaker against the shorter unstacked
        // parse of the same buffer. Decrement the inferred parse's
        // `syllableCount` by the number of injected `+`s so the count
        // reflects what the user perceives (a stacked compound is one
        // syllable, not two).
        // Skip stack inference when the lexicon already holds the exact
        // buffer — the curated form carries source=.lexicon, and a
        // parallel grammar parse with the same surface would steal the
        // lexicon source when the merge dedupes by surface. The
        // lexicon result is strictly better than anything inference
        // could add here, so bow out.
        var strictInferredStackOutputs: Set<String> = []
        if !hasExactLexiconMatch,
           let inferred = Self.inferImplicitStackMarkers(effectiveParseInput) {
            let existingOutputs = Set(grammarParses.map(\.output))
            // Add parses for the full inferred input (every `+` site).
            ingestInferredParses(
                input: inferred.input,
                insertions: inferred.insertions,
                liberalInsertions: inferred.liberalInsertions,
                isFullBuffer: !effectiveWindowed,
                grammarParses: &grammarParses,
                existingOutputs: existingOutputs,
                strictInferredStackOutputs: &strictInferredStackOutputs
            )
            // When the buffer mixes strict-valid (e.g. kinzi) and
            // liberal-only (cross-class Pali) inference sites, also
            // add parses for the strict-only inferred input. This
            // gives the ranker a clean kinzi/native-stack candidate
            // that doesn't carry the liberal cross-class virama
            // (task 04: prevent liberal sites from poisoning the
            // strict parse via shared structure/syllable scoring).
            if let strictOnly = inferred.strictOnlyInput {
                let outputsAfterFull = Set(grammarParses.map(\.output))
                ingestInferredParses(
                    input: strictOnly,
                    insertions: inferred.strictOnlyInsertions,
                    liberalInsertions: 0,
                    isFullBuffer: !effectiveWindowed,
                    grammarParses: &grammarParses,
                    existingOutputs: outputsAfterFull,
                    strictInferredStackOutputs: &strictInferredStackOutputs
                )
            }
        }
        // `windowFallback` is set when the tail-only parse failed so we
        // retried with the full buffer. In that case the anchor is still
        // the authoritative rendering of the prefix — we just couldn't
        // use windowing for this keystroke. We must not overwrite the
        // anchor with the fresh fallback top (which may have picked a
        // different decomposition driven by whole-buffer LM scores).
        var windowFallback = false
        if effectiveWindowed && grammarParses.allSatisfy({ !Self.isAcceptableParse($0) }) {
            effectiveParseInput = normalized
            effectivePrefixBranches = []
            effectiveWindowed = false
            windowFallback = true
            grammarParses = parser.parseCandidates(
                effectiveParseInput,
                maxResults: Self.grammarCandidateBudget(for: effectiveParseInput),
                isFullBuffer: !effectiveWindowed
            )
            grammarParses.removeAll { Self.hasInterleavedLatin($0.output) }
        }

        var grammarCandidates: [RankedGrammarCandidate]
        if effectiveWindowed {
            grammarCandidates = []
            grammarCandidates.reserveCapacity(grammarParses.count * effectivePrefixBranches.count)
            for branch in effectivePrefixBranches {
                for parse in grammarParses {
                    let surface = branch.output + parse.output
                    let reading = branch.reading + parse.reading
                    let tailLM = scoreSurfaceCached(parse.output, context: branch.contextWords, cache: &lmCache)
                    grammarCandidates.append(RankedGrammarCandidate(
                        candidate: Candidate(
                            surface: surface,
                            reading: reading,
                            source: .grammar,
                            score: Double(parse.score)
                        ),
                        legalityScore: parse.legalityScore,
                        aliasCost: parse.aliasCost,
                        parserScore: parse.score,
                        structureCost: parse.structureCost,
                        syllableCount: parse.syllableCount,
                        rarityPenalty: parse.rarityPenalty,
                        lmLogProb: branch.lmScore + tailLM,
                        absorbedMissingFromLM: false
                    ))
                }
            }
        } else {
            grammarCandidates = grammarParses.map { parse in
                RankedGrammarCandidate(
                    candidate: Candidate(
                        surface: parse.output,
                        reading: parse.reading,
                        source: .grammar,
                        score: Double(parse.score)
                    ),
                    legalityScore: parse.legalityScore,
                    aliasCost: parse.aliasCost,
                    parserScore: parse.score,
                    structureCost: parse.structureCost,
                    syllableCount: parse.syllableCount,
                    rarityPenalty: parse.rarityPenalty,
                    lmLogProb: scoreSurfaceCached(parse.output, context: context, cache: &lmCache),
                    absorbedMissingFromLM: false
                )
            }
        }
        // Two branches × tail can converge on the same surface. Keep the
        // higher-LM-scored copy so dedup doesn't drop the winning branch.
        if effectiveWindowed {
            var bestBySurface: [String: Int] = [:]
            var deduped: [RankedGrammarCandidate] = []
            for candidate in grammarCandidates {
                let key = candidate.candidate.surface
                if let existing = bestBySurface[key] {
                    if candidate.lmLogProb > deduped[existing].lmLogProb {
                        deduped[existing] = candidate
                    }
                } else {
                    bestBySurface[key] = deduped.count
                    deduped.append(candidate)
                }
            }
            grammarCandidates = deduped
        }
        // `hasInterleavedLatin` was already applied to `grammarParses` at
        // the two removeAll sites above (primary + window-fallback). The
        // windowed branch merely concatenates `branch.output` (frozen
        // prefix, Myanmar-only) with each already-filtered parse output,
        // so a repeat filter here cannot reject anything new.

        // Lexicon lookup runs BEFORE the grammar sort so that absorbed
        // lexicon scores (added to matching grammar candidates in place)
        // are visible to the composite-score comparator. Sorting first
        // and absorbing after leaves `candidate.score` stale during the
        // sort, which previously let surfaces like `မ်` (score 0) win
        // over `အံ` for buffer `an` even though absorption would boost
        // `အံ` to score ~643.
        //
        // When windowed, run one lexicon lookup against the active tail
        // and compose each hit with the frozen-prefix branches — otherwise
        // long sentences lose lexicon-corrected renderings entirely (the
        // tail-only parser produces literal digraphs like `s+h` where a
        // real word like `ရှ` should appear). Outside windowing, look up
        // the full buffer as before.
        let previousSurface = context.last
        let aliasPrefix = Romanization.aliasReading(normalized)
        let composePrefix = Romanization.composeLookupKey(normalized)
        let lexiconCandidates: [Candidate]
        if effectiveWindowed {
            let tailAlias = Romanization.aliasReading(effectiveParseInput)
            let branchPrevSurface = effectivePrefixBranches.first?.contextWords.last
                ?? previousSurface
            let tailHits = candidateStore.lookup(
                prefix: tailAlias,
                previousSurface: branchPrevSurface
            )
            // Only promote lexicon entries whose reading is exactly the
            // tail — partial prefix matches would drift keystroke-to-keystroke
            // and destabilize the frozen-prefix anchor for long sentences.
            let exactTailHits = tailHits.filter {
                Romanization.aliasReading($0.reading) == tailAlias
            }
            var composed: [Candidate] = []
            composed.reserveCapacity(exactTailHits.count * effectivePrefixBranches.count)
            for branch in effectivePrefixBranches {
                for hit in exactTailHits {
                    composed.append(Candidate(
                        surface: branch.output + hit.surface,
                        reading: branch.reading + hit.reading,
                        source: hit.source,
                        score: hit.score
                    ))
                }
            }
            lexiconCandidates = composed
        } else {
            lexiconCandidates = candidateStore.lookup(
                prefix: aliasPrefix,
                previousSurface: previousSurface
            )
        }

        // Word-lattice decoder (task: long-sentence quality debt). The
        // syllable-parser DP loses the LM-correct surface early in long
        // multi-word buffers because its beam prunes by alias cost — by
        // the time the engine's LM comparator runs, the right candidate
        // is no longer reachable. The lattice decoder reads the same
        // buffer through an arc graph (lexicon + syllable fallback)
        // with the LM in the Viterbi loop, so the correct surface
        // stays alive across word boundaries. Outputs land here as
        // first-class grammar candidates so the existing composite
        // / LM-dominance ranking picks between them and the parser
        // candidates on the usual signals.
        //
        // Length gate: for short buffers (below `latticeMinReadingLen`)
        // the parser + whole-buffer lexicon lookup already reach the
        // right answer, and lattice injection does more harm than good —
        // the lexicon carries rare pedagogical / Pali surfaces
        // (independent-vowel forms `ဦ`, `ဧ`, literary `ကြဧ`) whose raw
        // rank_score would win the synthetic-score comparison against
        // clean parser output. Gating at ≥8 chars keeps the lattice
        // focused on the multi-word regime where it actually moves the
        // needle.
        // Run the lattice decoder on the full normalized buffer, not
        // on the active tail. Windowed / frozen-prefix decoding can
        // commit a wrong parse in the prefix (e.g. `ဆစ်ဟွား` instead
        // of `ဆီသွား`) which the tail-only lattice cannot undo. Running
        // lattice on the full buffer lets it re-segment the whole
        // sentence in one pass — the lexicon's suffix cache
        // (`exactLookupCache`) keeps repeated keystrokes cheap.
        //
        // Because the lattice output represents the entire buffer
        // from scratch, we skip the frozen-prefix prepend path that
        // would otherwise apply in windowed mode.
        // The lattice needs a real (vocabulary-bearing) LM to rank
        // its word-arc alternatives — without one the Viterbi
        // collapses to "highest lexicon rank_score wins" and that
        // surfaces rare / literary variants (`တဦ` for `tu`, `ဦ`/`ဧ`
        // forms) in place of the common reading. Skip the decoder
        // under `NullLanguageModel` (tests that construct the engine
        // with just a store).
        let latticeOutputs: [WordLatticeDecoder.LatticeCandidate]
        if normalized.count >= Self.latticeMinReadingLen
            && languageModel.hasVocabulary {
            latticeOutputs = latticeDecoder.decode(
                reading: normalized,
                baseContext: context
            )
        } else {
            latticeOutputs = []
        }
        if !latticeOutputs.isEmpty {
            // Rebuild the surface index after each injection path; we
            // want lattice candidates to be deduped against existing
            // grammar candidates too.
            var injectIndex: [String: Int] = [:]
            for (idx, cand) in grammarCandidates.enumerated() {
                injectIndex[cand.candidate.surface] = idx
            }
            // Only inject lattice candidates whose LM score is within
            // a reasonable margin of the lattice's top. The tail of
            // the lattice output holds rare variants (retroflex `ဌ`,
            // tone-dot aliases, punctuation artefacts) that would
            // otherwise pollute the anchor history during progressive
            // typing — at an intermediate buffer length the weak-LM
            // variant can win a local tiebreak and then propagate as
            // the committed prefix on subsequent keystrokes.
            let latticeLmTop = latticeOutputs[0].lmLogProb
            let latticeLmFloor = latticeLmTop - Self.latticeLmInjectionMargin
            for (rank, out) in latticeOutputs.enumerated() where out.lmLogProb >= latticeLmFloor {
                let fullSurface = out.surface
                let fullReading = out.reading
                if Self.hasInterleavedLatin(fullSurface) { continue }
                // Lattice's Viterbi LM sum covers the whole buffer
                // (we run decode on `normalized`, not the windowed
                // tail). Use it as-is — arcwise trigram sum is the
                // ranking signal we want, aligned with the word
                // boundaries the lattice actually chose.
                let totalLM = out.lmLogProb
                // Synthetic rank score preserves the lattice's internal
                // order. Sized to be on the same scale as parser DP
                // scores (≤ 20 for a 10-char buffer): log(rank) is the
                // primary input to the composite comparator, and
                // `log(30) - log(10) = 1.1` is a ≈2.75 nat boost
                // against a pure parser candidate. That lets lattice
                // outputs surface in the top but still yields when
                // a parser candidate has a clearly better LM signal
                // (>≈3 nats, which the LM-dominance short-circuit
                // already covers at 1 nat). Top-of-lattice gets 30,
                // dropping by 2 per rank down to a floor of 10.
                let latticeRankScore = Double(max(10, 30 - rank * 2))
                if let existingIdx = injectIndex[fullSurface] {
                    // Same surface already emitted by parser / lexicon.
                    // Give it a modest lattice bonus (not full replace),
                    // and refresh the LM score with the lattice view so
                    // the absorbed candidate benefits from the decoder.
                    let existing = grammarCandidates[existingIdx]
                    grammarCandidates[existingIdx].candidate = Candidate(
                        surface: existing.candidate.surface,
                        reading: existing.candidate.reading,
                        source: existing.candidate.source,
                        score: existing.candidate.score + latticeRankScore
                    )
                    // Prefer the higher of the two LM readings — lattice
                    // uses the same scorer but a different context
                    // chain, so this is a safe max-of-both.
                    if totalLM > existing.lmLogProb {
                        grammarCandidates[existingIdx].lmLogProb = totalLM
                    }
                } else {
                    // Approximate Burmese syllable count by counting
                    // base consonants / independent vowels in the
                    // surface. Using `arcCount` directly under-reports
                    // for compound lexicon arcs (e.g. `အိမ်မှာ` = 1 arc
                    // but 2 syllables), which would let lattice win the
                    // DP-style `syllableCount` tiebreaker unfairly.
                    let approxSyllables = Self.approximateSyllableCount(fullSurface)
                    // Legality per syllable at 120 sits just above the
                    // parser's DP-score-per-syllable (100-110) so the
                    // lattice wins the legality tiebreak in
                    // `grammarCandidateIsBetter` at equal syllableCount.
                    // This is safe because every lattice arc is either a
                    // lexicon hit (curated surface) or a parser-emitted
                    // legal syllable — both are strictly as legal as the
                    // parser's own output.
                    grammarCandidates.append(RankedGrammarCandidate(
                        candidate: Candidate(
                            surface: fullSurface,
                            reading: fullReading,
                            source: .grammar,
                            score: latticeRankScore
                        ),
                        legalityScore: 120 * max(1, approxSyllables),
                        aliasCost: 0,
                        parserScore: Int(latticeRankScore),
                        structureCost: 0,
                        syllableCount: max(1, approxSyllables),
                        rarityPenalty: 0,
                        lmLogProb: totalLM,
                        absorbedMissingFromLM: false
                    ))
                    injectIndex[fullSurface] = grammarCandidates.count - 1
                }
            }
        }

        var grammarSurfaceIndex: [String: Int] = [:]
        for (index, candidate) in grammarCandidates.enumerated() {
            grammarSurfaceIndex[candidate.candidate.surface] = index
        }

        var uniqueLexiconCandidates: [RankedLexiconCandidate] = []
        var seenLexiconSurfaces: Set<String> = []

        for lexiconCandidate in lexiconCandidates {
            if let grammarIndex = grammarSurfaceIndex[lexiconCandidate.surface] {
                grammarCandidates[grammarIndex].candidate = Candidate(
                    surface: grammarCandidates[grammarIndex].candidate.surface,
                    reading: grammarCandidates[grammarIndex].candidate.reading,
                    source: .grammar,
                    score: grammarCandidates[grammarIndex].candidate.score + lexiconCandidate.score
                )
                if languageModel.hasVocabulary {
                    grammarCandidates[grammarIndex].absorbedMissingFromLM =
                        !languageModel.containsSurface(grammarCandidates[grammarIndex].candidate.surface)
                }
                continue
            }

            if seenLexiconSurfaces.insert(lexiconCandidate.surface).inserted {
                uniqueLexiconCandidates.append(
                    RankedLexiconCandidate(
                        candidate: lexiconCandidate,
                        aliasPenalty: Romanization.aliasPenaltyCount(for: lexiconCandidate.reading),
                        aliasReading: Romanization.aliasReading(lexiconCandidate.reading),
                        composeReading: Romanization.composeLookupKey(lexiconCandidate.reading),
                        lmLogProb: scoreSurfaceCached(lexiconCandidate.surface, context: context, cache: &lmCache)
                    )
                )
            }
        }

        // Sort after absorption so the comparator's composite score sees
        // the post-absorption `candidate.score`. Subsequent stages
        // (pruneByLmMargin, promoteAliasAlternate, alternate injection)
        // see a sorted list with the same shape they always did.
        grammarCandidates.sort { lhs, rhs in
            grammarCandidateIsBetter(lhs, than: rhs)
        }
        let appliesYapinPromotion = !effectiveWindowed
            && Self.isYapinPromotionBuffer(effectiveParseInput)

        if appliesYapinPromotion,
           let yapinSurface = Self.yapinPromotionPreservedSurface(
                in: grammarCandidates,
                userBuffer: effectiveParseInput
           ) {
            var preservingGrammarSurfaces = strictInferredStackOutputs
            preservingGrammarSurfaces.insert(yapinSurface)
            grammarCandidates = pruneGrammarByLmMargin(
                grammarCandidates,
                preservingSurfaces: preservingGrammarSurfaces
            )
        } else {
            grammarCandidates = pruneGrammarByLmMargin(
                grammarCandidates,
                preservingSurfaces: strictInferredStackOutputs
            )
        }
        grammarCandidates = promoteAliasAlternate(grammarCandidates)
        // Ya-pin typing-intent promotion: if the bare user buffer is
        // the exact digit-stripped form of a ya-pin canonical reading
        // (e.g. `kyay` → `ky2ay`), flip the top pick to the ya-pin
        // sibling (task 07). Only applied in the non-windowed path so
        // long-sentence frozen-prefix ranking is untouched.
        if appliesYapinPromotion {
            grammarCandidates = Self.promoteYapinForExactBareReading(
                grammarCandidates,
                userBuffer: effectiveParseInput
            )
        }

        // Expose disambiguation alternatives that the DP never emits
        // once the primary parse dominates:
        //
        //   * `<C>in+<C>` is a kinzi signal from the user, so the kinzi
        //     parse stays at rank 1 but the non-kinzi segmentation
        //     (`<C>in` + `<C>`) is injected as a lower-ranked option.
        //   * `<y|w|r|h><C>` promotes the leading medial-letter into
        //     an onset consonant silently; inject the buffer-minus-
        //     leading-letter parse so the user sees the "medial
        //     stranded" alternative.
        if !effectiveWindowed {
            let existingSurfaces = Set(grammarCandidates.map { $0.candidate.surface })
            var altInputs: [String] = []
            if let dropped = Self.dropKinziPlus(effectiveParseInput) { altInputs.append(dropped) }
            if let stripped = Self.stripLeadingMedialPromotion(effectiveParseInput) {
                altInputs.append(stripped)
            }
            var seenExtras = existingSurfaces
            for alt in altInputs {
                let altParses = parser.parseCandidates(
                    alt,
                    maxResults: 2,
                    isFullBuffer: !effectiveWindowed
                )
                for parse in altParses where !Self.hasInterleavedLatin(parse.output)
                    && !seenExtras.contains(parse.output) {
                    seenExtras.insert(parse.output)
                    grammarCandidates.append(RankedGrammarCandidate(
                        candidate: Candidate(
                            surface: parse.output,
                            reading: parse.reading,
                            source: .grammar,
                            score: Double(parse.score)
                        ),
                        legalityScore: parse.legalityScore,
                        aliasCost: parse.aliasCost,
                        parserScore: parse.score,
                        structureCost: parse.structureCost,
                        syllableCount: parse.syllableCount,
                        rarityPenalty: parse.rarityPenalty,
                        lmLogProb: scoreSurfaceCached(parse.output, context: context, cache: &lmCache),
                        absorbedMissingFromLM: false
                    ))
                }
            }
        }

        // History lookup uses the same alias key as the lexicon so stored
        // reads (written by `recordSelection`) line up exactly with reads.
        // Unlike lexicon candidates, history entries carry a self-contained
        // surface that isn't composed with the frozen prefix, so they are
        // safe to surface even when windowing is active — otherwise a user
        // who committed a long phrase once wouldn't see it again the next
        // time they typed the same reading (the buffer crosses the window
        // threshold long before they reach the end).
        let historyEnabled = settings?.learningEnabled ?? true
        let historyCandidates: [Candidate] = historyEnabled
            ? historyStore.lookup(prefix: aliasPrefix, previousSurface: previousSurface)
            : []
        cacheLock.lock()
        lastHistoryKey = aliasPrefix
        cacheLock.unlock()

        uniqueLexiconCandidates.sort { lhs, rhs in
            lexiconCandidateIsBetter(lhs, than: rhs, aliasPrefix: aliasPrefix, composePrefix: composePrefix)
        }
        uniqueLexiconCandidates = pruneByLmMargin(uniqueLexiconCandidates, keyPath: \.lmLogProb)

        let primaryGrammar = Array(grammarCandidates.prefix(3))
        let remainingGrammar = Array(grammarCandidates.dropFirst(3))
        let exactAliasLexicon = uniqueLexiconCandidates.filter { $0.aliasReading == aliasPrefix }
        let exactComposeLexicon = uniqueLexiconCandidates.filter {
            $0.aliasReading != aliasPrefix && $0.composeReading == composePrefix
        }
        let prioritizedLexicon = Array(
            (exactAliasLexicon.isEmpty ? exactComposeLexicon : exactAliasLexicon)
                .prefix(2)
        )
        let prioritizedKeys = Set(prioritizedLexicon.map(lexiconCandidateKey))
        let trailingLexicon = uniqueLexiconCandidates.filter { !prioritizedKeys.contains(lexiconCandidateKey($0)) }

        let promotedYapinGrammarFirst = appliesYapinPromotion
            && primaryGrammar.first.map { Self.isYapinReading($0.candidate.reading) } == true

        var merged: [Candidate]
        let primaryGrammarStart: Int
        if promotedYapinGrammarFirst, let firstGrammar = primaryGrammar.first {
            merged = []
            merged.append(firstGrammar.candidate)
            primaryGrammarStart = 1
            for lexiconCandidate in prioritizedLexicon where merged.count < candidatePageSize {
                if !merged.contains(where: { $0.surface == lexiconCandidate.candidate.surface }) {
                    merged.append(lexiconCandidate.candidate)
                }
            }
        } else {
            merged = prioritizedLexicon.map(\.candidate)
            primaryGrammarStart = 0
        }

        if primaryGrammarStart == 0 {
            for grammarCandidate in primaryGrammar where merged.count < candidatePageSize {
                merged.append(grammarCandidate.candidate)
            }
        } else {
            for grammarCandidate in primaryGrammar.dropFirst(primaryGrammarStart) where merged.count < candidatePageSize {
                merged.append(grammarCandidate.candidate)
            }
        }

        for lexiconCandidate in trailingLexicon where merged.count < candidatePageSize {
            merged.append(lexiconCandidate.candidate)
        }

        for grammarCandidate in remainingGrammar where merged.count < candidatePageSize {
            merged.append(grammarCandidate.candidate)
        }

        // History promotion: the user previously committed these surfaces
        // under the same alias key, so float them to the top. Walk lowest
        // score first so the highest-scoring history entry lands at index 0
        // after successive front-inserts. Surfaces already in `merged` are
        // moved; unseen surfaces are injected (the entry was legal when
        // first committed, so it's safe to resurface).
        for historyCandidate in historyCandidates.sorted(by: { $0.score < $1.score }) {
            if let existing = merged.firstIndex(where: { $0.surface == historyCandidate.surface }) {
                let keeper = merged.remove(at: existing)
                merged.insert(keeper, at: 0)
            } else {
                merged.insert(historyCandidate, at: 0)
            }
        }

        merged = Self.expandAaVariants(merged)
        merged = Self.sanitizeOrphanZwnj(merged)
        merged = Self.sanitizeMalformedMyanmarMarks(merged)

        if !effectiveParseInput.contains("+"),
           !effectiveWindowed,
           !strictInferredStackOutputs.isEmpty,
           let idx = Self.bestStrictInferredStackIndex(
               in: merged,
               strictInferredStackOutputs: strictInferredStackOutputs
           ) {
            let keeper = merged.remove(at: idx)
            merged.insert(keeper, at: 0)
        }

        // Pali loanword fallback: cross-class virama stacks like
        // ပဒ္မ / ဗန္ဒန / ဂန္ဒ are not produced by Grammar.isValidStack
        // (which is restricted to native same-class pairs) and are not
        // present as lexicon entries when the corpus does not surface
        // them. Inject the canonical stacked surface at rank 1 for the
        // exact bare reading so the engine returns the orthographic
        // form a typist reaches for. Compound buffers that just happen
        // to start with one of these readings (e.g. `gandakar`) match
        // the regular grammar/lexicon path and never hit this branch.
        if let paliSurface = Self.paliStackOverrideSurface(for: normalized) {
            if let existing = merged.firstIndex(where: { $0.surface == paliSurface }) {
                let keeper = merged.remove(at: existing)
                merged.insert(keeper, at: 0)
            } else {
                merged.insert(Candidate(
                    surface: paliSurface,
                    reading: normalized,
                    source: .grammar,
                    score: 100
                ), at: 0)
            }
        }

        // Bare-vowel override: `i` → အိ, `ee` → အီ. Grammar siblings
        // (`ည်`, `ယ်ယ်`, long-i / short-i) remain in the panel — this
        // only flips the top (task 08).
        if let bareVowelSurface = Self.bareVowelOverrideSurface(for: normalized) {
            if let existing = merged.firstIndex(where: { $0.surface == bareVowelSurface }) {
                let keeper = merged.remove(at: existing)
                merged.insert(keeper, at: 0)
            } else {
                merged.insert(Candidate(
                    surface: bareVowelSurface,
                    reading: normalized,
                    source: .grammar,
                    score: 100
                ), at: 0)
            }
        }

        // Anchor promotion: when the top candidate drifts away from a
        // previously established prefix, promote any candidate that
        // preserves the anchor surface. Walk the anchor history from
        // deepest to shallowest: intermediate anchors may have held
        // temporarily wrong syllable decompositions (e.g. "kah" → ကအ
        // before "kaht" → ကထ resolved), so skip those and find the
        // deepest anchor whose surface actually appears in a candidate.
        // Surface comparison strips ZWSPs because lexicon entries may
        // contain U+200B word-boundary markers that grammar-generated
        // surfaces lack.
        //
        // A history-sourced top outranks anchor stability: the user
        // explicitly committed that surface previously, so displacing it
        // with a parser-derived anchor extension would revert a deliberate
        // pick.
        if !merged.isEmpty, merged[0].source != .history {
            var promoted = false
            for anchor in historySnapshot.reversed() {
                guard !anchor.normalized.isEmpty,
                      normalized.hasPrefix(anchor.normalized),
                      normalized.count > anchor.normalized.count,
                      anchor.normalized.count >= anchorCommitThreshold
                else { continue }
                let anchorKey = Self.stripZWSP(anchor.surface)
                // Already matching — no promotion needed.
                if Self.scalarHasPrefix(Self.stripZWSP(merged[0].surface), anchorKey) {
                    promoted = true
                    break
                }
                if let idx = merged.firstIndex(where: { Self.scalarHasPrefix(Self.stripZWSP($0.surface), anchorKey) }) {
                    let keeper = merged.remove(at: idx)
                    merged.insert(keeper, at: 0)
                    promoted = true
                    break
                }
            }
            // No existing candidate matched any anchor. The full-buffer
            // parse has the correct syllable structure but may have
            // drifted in ya-pin/ya-yit medial choice. Check whether the
            // difference is only in medials — if so, create a variant
            // with the anchor's medial swapped in. This preserves the
            // correct syllable count while keeping the user's previously-
            // seen prefix stable on screen.
            if !promoted {
                let topStripped = Self.stripZWSP(merged[0].surface)
                for anchor in historySnapshot.reversed() {
                    guard !anchor.normalized.isEmpty,
                          normalized.hasPrefix(anchor.normalized),
                          normalized.count > anchor.normalized.count,
                          anchor.normalized.count >= anchorCommitThreshold
                    else { continue }
                    let anchorStripped = Self.stripZWSP(anchor.surface)
                    if Self.viramaInsensitiveHasPrefix(topStripped, anchorStripped)
                        && !Self.scalarHasPrefix(topStripped, anchorStripped) {
                        let variant = Self.substituteViramaAnchor(
                            in: merged[0].surface,
                            matching: anchorStripped
                        )
                        merged.insert(Candidate(
                            surface: variant,
                            reading: merged[0].reading,
                            source: merged[0].source,
                            score: merged[0].score
                        ), at: 0)
                        break
                    }
                    // Check if the surfaces match after normalizing
                    // ya-pin (U+103B) ↔ ya-yit (U+103C) medials.
                    let topNorm = Self.normalizeYaPinYaYit(topStripped)
                    let anchorNorm = Self.normalizeYaPinYaYit(anchorStripped)
                    if topNorm.hasPrefix(anchorNorm)
                        && !topStripped.hasPrefix(anchorStripped) {
                        let variant = Self.substituteMedials(
                            in: merged[0].surface,
                            matching: anchorStripped
                        )
                        merged.insert(Candidate(
                            surface: variant,
                            reading: merged[0].reading,
                            source: merged[0].source,
                            score: merged[0].score
                        ), at: 0)
                        break
                    }
                }
            }
        }

        // Record the new anchor for the next update. Capturing the top
        // candidate's (normalized, surface, reading) means subsequent
        // keystrokes that extend `normalized` reuse this exact rendering
        // rather than re-parsing and potentially picking a different
        // decomposition. During a window-fallback we keep the existing
        // anchor — the rendering the user still sees on screen — rather
        // than committing the fallback top that may have drifted.
        if !windowFallback {
            cacheLock.lock()
            // Skip history candidates when picking the anchor: their surface
            // is the full stored rendering for a longer reading that still
            // begins with the currently-typed prefix, so capturing it as
            // the anchor for `normalized` pairs a short key with an overly
            // long surface. A later windowed update would reuse that anchor
            // as a frozen prefix and concatenate a fresh tail parse,
            // producing candidates shaped like `<full history surface> +
            // <tail re-rendered>`. The non-history top reflects the actual
            // syllable rendering of the typed chars and is safe to anchor.
            if let top = merged.first(where: { $0.source != .history }) {
                // Prune prior entries that are stale: either (a) their
                // normalized is not a prefix of the current buffer (user
                // backspaced/diverged), or (b) their surface is not a
                // prefix of the new top's surface (an intermediate
                // decomposition that was superseded — e.g. step 11 "kah"
                // → ကအ gets pruned when step 12 "kaht" → ကထ resolves
                // differently). This prevents stale anchors from being
                // used in synthesis and producing extra syllable splits.
                let topStripped = Self.stripZWSP(top.surface)
                let topScalars = Array(topStripped.unicodeScalars)
                anchorHistory.removeAll { anchor in
                    if !normalized.hasPrefix(anchor.normalized) { return true }
                    let anchorStripped = Self.stripZWSP(anchor.surface)
                    if !Self.scalarHasPrefix(topStripped, anchorStripped) { return true }
                    // Anchor's last consonant or medial was extended by
                    // an additional sign in the new top (e.g. anchor
                    // `...ဘ` followed by a medial `ြ` in top `...ဘြ`, or
                    // anchor `...ပြ` followed by a vowel `ီ` in top
                    // `...ပြီ`). Reusing that stale anchor would prevent
                    // the extension from forming in subsequent windowing.
                    let anchorScalarCount = anchorStripped.unicodeScalars.count
                    if anchorScalarCount > 0,
                       anchorScalarCount < topScalars.count,
                       let last = anchorStripped.unicodeScalars.last,
                       Myanmar.isConsonant(last) || Myanmar.isMedial(last),
                       Self.isMedialOrMarker(topScalars[anchorScalarCount]) {
                        return true
                    }
                    return false
                }
                // Replace the last entry if it has the same normalized
                // length (we're updating the same checkpoint, not adding).
                if let last = anchorHistory.last, last.normalized == normalized {
                    anchorHistory.removeLast()
                }
                anchorHistory.append(PrefixAnchor(
                    normalized: normalized,
                    surface: top.surface,
                    reading: top.reading
                ))
                if anchorHistory.count > Self.maxAnchorHistory {
                    anchorHistory.removeFirst(anchorHistory.count - Self.maxAnchorHistory)
                }
            }
            cacheLock.unlock()
        }

        // Attach leading literal, digit prefix, and literal tail to each
        // candidate surface.
        let hasAffixes = !leadingLiteral.isEmpty || !digitPrefix.isEmpty || !effectiveTail.isEmpty
        let mergedWithAffixes: [Candidate]
        if !hasAffixes {
            mergedWithAffixes = merged
        } else {
            let burmesePrefix = Self.arabicToBurmeseDigits(digitPrefix)
            var expanded: [Candidate] = []
            var seen: Set<String> = []
            for candidate in merged {
                let candidateTail = effectiveTail
                let hasDigitAffixes = Self.containsDigit(digitPrefix) || Self.containsDigit(candidateTail)
                if leadingLiteral.isEmpty && digitPrefix.isEmpty && candidateTail.isEmpty {
                    if seen.insert(candidate.surface).inserted {
                        expanded.append(candidate)
                    }
                    continue
                }
                if hasDigitAffixes {
                    let primary = leadingLiteral + burmesePrefix + candidate.surface + Self.arabicToBurmeseDigits(candidateTail)
                    if seen.insert(primary).inserted {
                        expanded.append(Candidate(
                            surface: primary,
                            reading: candidate.reading,
                            source: candidate.source,
                            score: candidate.score
                        ))
                    }
                    let secondary = leadingLiteral + digitPrefix + candidate.surface + candidateTail
                    if secondary != primary, seen.insert(secondary).inserted {
                        expanded.append(Candidate(
                            surface: secondary,
                            reading: candidate.reading,
                            source: candidate.source,
                            score: candidate.score
                        ))
                    }
                } else {
                    let surface = leadingLiteral + digitPrefix + candidate.surface + candidateTail
                    if seen.insert(surface).inserted {
                        expanded.append(Candidate(
                            surface: surface,
                            reading: candidate.reading,
                            source: candidate.source,
                            score: candidate.score
                        ))
                    }
                }
            }
            mergedWithAffixes = expanded
        }

        let sanitizedWithAffixes = Self.sanitizeMalformedMyanmarMarks(mergedWithAffixes)
        let finalCandidates: [Candidate]
        if leadingLiteral.isEmpty,
           digitPrefix.isEmpty,
           literalTail.isEmpty,
           droppedTailHasAsciiLetters {
            finalCandidates = sanitizedWithAffixes.filter {
                !Self.containsAsciiSurfaceScalar($0.surface)
                    && SyllableParser.scanOutputLegality($0.surface)
            }
        } else {
            finalCandidates = sanitizedWithAffixes
        }

        return CompositionState(
            rawBuffer: displayBuffer,
            selectedCandidateIndex: 0,
            candidates: finalCandidates,
            committedContext: context
        )
    }

    /// Run the inferred-`+` parses for `input`, neutralise the
    /// per-`+` bookkeeping bumps so the inferred parse competes with
    /// the no-`+` parse on real merits, and push the result into
    /// `grammarParses` (skipping outputs already present). Used twice
    /// per buffer when `inferImplicitStackMarkers` returns both a
    /// full-site and a strict-only inferred form.
    internal func ingestInferredParses(
        input: String,
        insertions: Int,
        liberalInsertions: Int,
        isFullBuffer: Bool,
        grammarParses: inout [SyllableParse],
        existingOutputs: Set<String>,
        strictInferredStackOutputs: inout Set<String>
    ) {
        let inferredParses = stackInferenceParses(input, isFullBuffer: isFullBuffer)
        for parse in inferredParses
        where !Self.hasInterleavedLatin(parse.output) {
            // Neutralise the bookkeeping bump each injected `+` adds:
            // the parser treats a soft-boundary transition as a new
            // vowel slot, so it contributes +1 `syllableCount` and a
            // per-syllable `legalityScore` step (~+100) regardless of
            // whether the site actually stacked. Reverting both keeps
            // the inferred parse on equal footing with the original
            // no-`+` parse, so the two compete on their real merits
            // (parser score, alias cost, LM) rather than on ghost
            // legality the `+` produced.
            let adjustedCount = max(1, parse.syllableCount - insertions)
            let adjustedLegality = parse.legalityScore > 0
                ? max(1, parse.legalityScore - 100 * insertions)
                : parse.legalityScore
            // Bump rarityPenalty per liberal (cross-class) insertion
            // when the buffer doesn't look like a Pali/Sanskrit
            // transliteration. Cross-class virama stacks are Pali
            // loanword territory; ordinary Burmese compounds like
            // `takmaung`, `pakta`, `kakna` produce the same
            // liberal-only `+` sites and should *not* render with a
            // virama at top. The `r` letter is a reliable Pali
            // transliteration hint — `karma`, `dharma`, `brahma`,
            // `yarpadma` all carry it; the over-generating Burmese
            // compounds typically don't. Buffers with no `r` get a
            // rarity bump that demotes the liberal-stacked form
            // below the no-stack sibling. The stacked form stays in
            // the panel as a lower-ranked option, and `padma` /
            // `vandana` / `ganda`-style Pali loanwords with override
            // entries are unaffected (they're injected at rank 0
            // independently of inference). See task 04.
            let prefixHasPaliR = input.contains("r")
            let liberalRarityBump = (liberalInsertions > 0 && !prefixHasPaliR)
                ? 5 * liberalInsertions
                : 0
            let adjusted = SyllableParse(
                output: parse.output,
                reading: parse.reading,
                aliasCost: parse.aliasCost + 10 * liberalInsertions,
                legalityScore: adjustedLegality,
                score: parse.score,
                structureCost: parse.structureCost + liberalInsertions,
                syllableCount: adjustedCount,
                rarityPenalty: parse.rarityPenalty + liberalRarityBump
            )
            if liberalInsertions == 0,
               Self.surfaceHasOnlyNativeViramaStacks(adjusted.output) {
                strictInferredStackOutputs.insert(adjusted.output)
                strictInferredStackOutputs.insert(Self.correctAaShape(adjusted.output))
            }
            if !existingOutputs.contains(adjusted.output) {
                grammarParses.append(adjusted)
            }
        }
    }

    internal func stackInferenceParses(
        _ input: String,
        isFullBuffer: Bool
    ) -> [SyllableParse] {
        cacheLock.lock()
        if let idx = stackInferenceParseCache.firstIndex(where: {
            $0.input == input && $0.isFullBuffer == isFullBuffer
        }) {
            let entry = stackInferenceParseCache.remove(at: idx)
            stackInferenceParseCache.insert(entry, at: 0)
            cacheLock.unlock()
            return entry.parses
        }
        cacheLock.unlock()

        let parses = parser.parseCandidates(
            input,
            maxResults: Self.stackInferenceBudget,
            isFullBuffer: isFullBuffer,
            allowLiberalStacks: true
        )

        cacheLock.lock()
        stackInferenceParseCache.insert(StackInferenceParseCache(
            input: input,
            isFullBuffer: isFullBuffer,
            parses: parses
        ), at: 0)
        if stackInferenceParseCache.count > Self.maxStackInferenceParseCache {
            stackInferenceParseCache.removeLast(
                stackInferenceParseCache.count - Self.maxStackInferenceParseCache
            )
        }
        cacheLock.unlock()
        return parses
    }

    private static func bestStrictInferredStackIndex(
        in candidates: [Candidate],
        strictInferredStackOutputs: Set<String>
    ) -> Int? {
        var bestIndex: Int?
        for (idx, candidate) in candidates.enumerated()
        where strictInferredStackOutputs.contains(candidate.surface) {
            guard let current = bestIndex else {
                bestIndex = idx
                continue
            }
            let currentCandidate = candidates[current]
            let candidateHasKinzi = surfaceContainsKinzi(candidate.surface)
            let currentHasKinzi = surfaceContainsKinzi(currentCandidate.surface)
            if candidate.score > currentCandidate.score
                || (candidate.score == currentCandidate.score && candidateHasKinzi && !currentHasKinzi) {
                bestIndex = idx
            }
        }
        return bestIndex
    }

    private static func surfaceContainsKinzi(_ surface: String) -> Bool {
        let scalars = surface.unicodeScalars.map(\.value)
        guard scalars.count >= 3 else { return false }
        for idx in 0...(scalars.count - 3)
        where scalars[idx] == 0x1004
            && scalars[idx + 1] == 0x103A
            && scalars[idx + 2] == 0x1039 {
            return true
        }
        return false
    }

    /// Commit the currently selected candidate.
    /// Returns the committed surface text: the selected candidate for the
    /// convertible prefix, followed by any unconverted tail from the raw
    /// buffer emitted verbatim.
    public func commit(state: CompositionState) -> String {
        guard !state.candidates.isEmpty,
              state.selectedCandidateIndex < state.candidates.count else {
            return state.rawBuffer
        }
        // Candidate surfaces already include the literal tail (appended in
        // update()), so committing the selection emits both parts together.
        return state.candidates[state.selectedCandidateIndex].surface
    }

    /// Record the user's selection in the history store so it can be
    /// promoted on subsequent compositions. Writes the alias-normalized
    /// lookup key captured by the most recent `update` call — matching what
    /// `lookup` will see next time the same reading is typed. No-op when
    /// learning is disabled or the state has no active selection.
    public func recordSelection(state: CompositionState) {
        guard settings?.learningEnabled ?? true else { return }
        guard !state.candidates.isEmpty,
              state.selectedCandidateIndex < state.candidates.count else {
            return
        }
        let candidate = state.candidates[state.selectedCandidateIndex]
        // History-sourced picks must bump the existing row rather than
        // creating a new shortcut keyed on whatever prefix was typed —
        // otherwise picking a long history entry via a short prefix would
        // pollute the table with partial-key duplicates.
        let key: String
        if candidate.source == .history, !candidate.reading.isEmpty {
            key = candidate.reading
        } else {
            cacheLock.lock()
            key = lastHistoryKey
            cacheLock.unlock()
        }
        guard !key.isEmpty else { return }
        historyStore.record(reading: key, surface: candidate.surface)
    }

    /// Cancel composition: return the raw buffer unchanged.
    public func cancel(state: CompositionState) -> String {
        state.rawBuffer
    }
}
