import Foundation

/// The main composition engine for the Burmese IME.
///
/// Manages the composition buffer, generates candidates from grammar parsing
/// and lexicon lookup, and handles commit/cancel operations.
///
/// Ranking order: grammar legality > alias cost > LM log-prob > parser score
/// > lexicon frequency. The LM replaces the earlier hand-tuned bigram
/// boost — see `Packages/BurmeseIMECore/Sources/BurmeseIMECore/LanguageModel/FORMAT.md`.
public final class BurmeseEngine: @unchecked Sendable {

    private struct RankedGrammarCandidate {
        var candidate: Candidate
        let legalityScore: Int
        let aliasCost: Int
        let parserScore: Int
        let structureCost: Int
        let syllableCount: Int
        let rarityPenalty: Int
        var lmLogProb: Double
    }

    private struct RankedLexiconCandidate {
        let candidate: Candidate
        let aliasPenalty: Int
        let aliasReading: String
        let composeReading: String
        let lmLogProb: Double
    }

    /// Number of N-best parses requested from `SyllableParser` per keystroke.
    /// This is the pool the LM re-ranks; candidates ranked beyond this by the
    /// parser's own score never reach the LM, so it must be large enough to
    /// include plausible medial/onset alternates. The parser's internal beam
    /// scales to `max(budget × 16, 64)`, so a budget of 64 keeps the beam
    /// ≈1024 — still comfortably sub-millisecond on an M-series Mac.
    private static let grammarCandidateBudget = 24

    /// Maximum natural-log-probability gap a candidate may trail the best
    /// LM-ranked candidate before being dropped. 8 ≈ factor ~3000×; well
    /// below that and the candidate is almost certainly nonsense noise
    /// generated by the parser. Keeps the panel to plausible picks only.
    /// Used as the fallback when no `IMESettings` instance is supplied.
    private static let lmPruneMarginDefault: Double = 8.0

    private let parser: SyllableParser
    private let candidateStore: any CandidateStore
    private let historyStore: any UserHistoryStore
    private let languageModel: any LanguageModel

    /// Sliding-window threshold for the full N-best parse. When the
    /// normalized buffer exceeds this, everything before the trailing
    /// window is rendered once via a cheap single-best parse and cached;
    /// only the tail is re-parsed on each keystroke. The window covers
    /// `maxOnsetLen + maxVowelLen` plus a safety margin so no rule can
    /// span the prefix/tail boundary.
    private let compositionWindowSize: Int

    /// Top-K LM-scored renderings of the frozen prefix. Caching K branches
    /// (instead of a single rendering) lets the engine surface alternative
    /// interpretations of the locked-in prefix in the candidate panel:
    /// each branch combines with each tail parse, and the overall LM score
    /// of (branch + tail) decides ranking.
    private struct FrozenPrefixBranch {
        let output: String
        let reading: String
        let lmScore: Double
        /// Pre-tokenized branch words used as LM context for the tail.
        let contextWords: [String]
    }
    private struct FrozenPrefixCache {
        var input: String
        var branches: [FrozenPrefixBranch]
    }
    /// Small LRU (most-recent-first). Survives backspace-then-retype without
    /// re-parsing the frozen prefix. Capacity is deliberately tiny — each
    /// entry is one parse plus its branches (typically K=1), and linear scan
    /// at this size is cheaper than dictionary overhead.
    private var prefixCache: [FrozenPrefixCache] = []
    private static let frozenPrefixCacheCapacity = 8
    private let cacheLock = NSLock()

    /// Anchor remembered across `update()` calls to keep the rendered
    /// prefix stable. When the new normalized buffer extends the anchor's
    /// `normalized`, any candidate whose surface starts with the anchor's
    /// `surface` is promoted to the top — so the already-visible rendering
    /// of the typed-so-far portion doesn't drift as the user adds more
    /// characters. Cleared when the buffer no longer extends the anchor
    /// (e.g. backspace past it, or a new composition).
    private struct PrefixAnchor {
        let normalized: String
        let surface: String
        let reading: String
    }
    /// History of anchors (checkpoints) ordered by `normalized.count`.
    /// When the latest/deepest anchor's tail can't parse standalone
    /// (e.g. a single "a" or ":"), we fall back to an earlier checkpoint
    /// whose tail is long enough to parse. This keeps the rendered
    /// prefix stable even across intermediate strokes where the tail
    /// alone is ambiguous.
    private var anchorHistory: [PrefixAnchor] = []
    private static let maxAnchorHistory = 32

    /// Last alias-normalized lookup key produced by `update`. Captured under
    /// `cacheLock` so `recordSelection` can write the same key the lexicon
    /// and history stores would have seen on lookup — keeping write/read
    /// symmetric without plumbing the key through `CompositionState`.
    private var lastHistoryKey: String = ""

    /// Number of frozen-prefix branches kept and combined with each
    /// tail parse. Higher = more chances to recover from a parser-favored
    /// but LM-disfavored prefix; cost scales linearly in tail-merge work.
    private static let frozenPrefixBranchCount = 1

    /// Upper bound on the active-tail length before the frozen prefix is
    /// extended forward. Keeping this larger than `compositionWindowSize`
    /// means an already-chosen prefix stays stable for many keystrokes —
    /// the committed portion the user sees doesn't shift as they type.
    /// Only when the tail reaches this size do we advance the split point.
    private static let maxActiveTailSize = 40

    /// Roman-input length past which a previously-rendered top candidate
    /// is treated as "committed" and will not be re-parsed on subsequent
    /// keystrokes. Below this, the engine always performs a fresh full-
    /// buffer parse so that early ambiguous picks (e.g. `k`, `kw`, `kwy`
    /// before medials can be disambiguated) can be overwritten by a
    /// clearly better interpretation once enough characters exist. At or
    /// above this length, the LM had real evidence when selecting the
    /// anchor, so we lock it to prevent the committed portion from
    /// silently drifting under the user.
    /// Fallback used when no `IMESettings` instance is supplied.
    private static let anchorCommitThresholdDefault = 8

    /// Page size for candidate display. Fallback used when no `IMESettings`
    /// instance is supplied.
    public static let candidatePageSizeDefault = 9

    private let settings: IMESettings?

    /// Live-read wrapper. Falls back to the static default when no settings
    /// instance is wired; otherwise reflects the shared UserDefaults value,
    /// so the IMK extension sees changes without an engine rebuild.
    public var candidatePageSize: Int {
        settings?.candidatePageSize ?? Self.candidatePageSizeDefault
    }
    private var lmPruneMargin: Double {
        settings?.lmPruneMargin ?? Self.lmPruneMarginDefault
    }
    private var anchorCommitThreshold: Int {
        settings?.anchorCommitThreshold ?? Self.anchorCommitThresholdDefault
    }
    private var burmesePunctuationEnabled: Bool {
        settings?.burmesePunctuationEnabled ?? false
    }

    public init(
        candidateStore: any CandidateStore = EmptyCandidateStore(),
        historyStore: any UserHistoryStore = EmptyUserHistoryStore(),
        languageModel: any LanguageModel = NullLanguageModel(),
        settings: IMESettings? = nil
    ) {
        let useClusterAliases = settings?.clusterAliasesEnabled ?? true
        let parser = SyllableParser(useClusterAliases: useClusterAliases)
        self.parser = parser
        self.candidateStore = candidateStore
        self.historyStore = historyStore
        self.languageModel = languageModel
        self.settings = settings
        // Active-tail size in Roman chars. Once the buffer exceeds this,
        // everything before a syllable-safe boundary is parsed once and
        // cached (the "frozen prefix"); subsequent keystrokes only re-parse
        // the trailing window. A naïve character-count split was the source
        // of the earlier "garbage variants past the threshold" bug — the
        // split now snaps back to the nearest position where the prefix
        // parses fully legally on its own, so it never cuts mid-syllable.
        self.compositionWindowSize = 20
    }

    /// Pool of parser N-best parses considered for the frozen prefix
    /// before LM-rescoring picks the top-K branches.
    private static let frozenPrefixCandidatePool = 16

    /// Call-scoped memo key for LM `scoreSurface` lookups.
    private struct LMScoreKey: Hashable {
        let surface: String
        let context: [String]
    }

    private func renderFrozenPrefixBranches(
        _ prefix: String,
        baseContext: [String],
        lmCache: inout [LMScoreKey: Double]
    ) -> [FrozenPrefixBranch] {
        cacheLock.lock()
        if let hitIdx = prefixCache.firstIndex(where: { $0.input == prefix }) {
            let entry = prefixCache.remove(at: hitIdx)
            prefixCache.insert(entry, at: 0)
            let branches = entry.branches
            cacheLock.unlock()
            return branches
        }
        cacheLock.unlock()

        let parses = parser.parseCandidates(prefix, maxResults: Self.frozenPrefixCandidatePool)
        let branches: [FrozenPrefixBranch]
        if parses.isEmpty {
            branches = [FrozenPrefixBranch(
                output: prefix,
                reading: prefix,
                lmScore: scoreSurfaceCached(prefix, context: baseContext, cache: &lmCache),
                contextWords: [prefix]
            )]
        } else {
            // Dedup parses by output (different parses can render identically),
            // score each via the LM, sort high-to-low, keep top K.
            var seen: Set<String> = []
            var scored: [FrozenPrefixBranch] = []
            for parse in parses where seen.insert(parse.output).inserted {
                let lm = scoreSurfaceCached(parse.output, context: baseContext, cache: &lmCache)
                scored.append(FrozenPrefixBranch(
                    output: parse.output,
                    reading: parse.reading,
                    lmScore: lm,
                    contextWords: baseContext + [parse.output]
                ))
            }
            scored.sort { $0.lmScore > $1.lmScore }
            // Drop branches whose LM score is far below the leader before
            // fanning out — otherwise weak prefix interpretations multiply
            // across every tail parse and flood the candidate panel.
            if let topScore = scored.first?.lmScore {
                scored = scored.filter { topScore - $0.lmScore <= lmPruneMargin }
            }
            branches = Array(scored.prefix(Self.frozenPrefixBranchCount))
        }

        cacheLock.lock()
        prefixCache.removeAll(where: { $0.input == prefix })
        prefixCache.insert(FrozenPrefixCache(input: prefix, branches: branches), at: 0)
        if prefixCache.count > Self.frozenPrefixCacheCapacity {
            prefixCache.removeLast(prefixCache.count - Self.frozenPrefixCacheCapacity)
        }
        cacheLock.unlock()
        return branches
    }

    private func scoreSurfaceCached(
        _ surface: String,
        context: [String],
        cache: inout [LMScoreKey: Double]
    ) -> Double {
        let key = LMScoreKey(surface: surface, context: context)
        if let hit = cache[key] { return hit }
        let score = languageModel.scoreSurface(surface, context: context)
        cache[key] = score
        return score
    }

    /// Update the composition state based on the current buffer and context.
    /// Called on every keystroke that modifies the buffer.
    public func update(buffer: String, context: [String]) -> CompositionState {
        guard !buffer.isEmpty else {
            cacheLock.lock()
            anchorHistory.removeAll()
            lastHistoryKey = ""
            cacheLock.unlock()
            return CompositionState(committedContext: context)
        }
        let displayBuffer = buffer.lowercased()
        // If punct mapping is on and the buffer contains a mapped-punct
        // char that is NOT just at the very tail, everything up to and
        // including the *last* such punct becomes a frozen rendering
        // (each composable run resolved via single-best parse, punct
        // chars replaced with their Myanmar equivalents). We then recurse
        // on the active suffix so the current word still gets N-best
        // candidates, and prepend the frozen prefix to every surface.
        if burmesePunctuationEnabled,
           let split = splitAtLastEmbeddedMappedPunct(displayBuffer) {
            var state = update(buffer: split.activeBuffer, context: context)
            state.rawBuffer = displayBuffer
            if state.candidates.isEmpty {
                // Active portion produced nothing parseable; surface the
                // frozen prefix + raw active so the user still sees the
                // settled portion and doesn't lose their composition.
                state.candidates = [Candidate(
                    surface: split.renderedPrefix + split.activeBuffer,
                    reading: displayBuffer,
                    source: .grammar,
                    score: 0
                )]
            } else {
                state.candidates = state.candidates.map { cand in
                    Candidate(
                        surface: split.renderedPrefix + cand.surface,
                        reading: cand.reading,
                        source: cand.source,
                        score: cand.score
                    )
                }
            }
            return state
        }
        // Strip leading ASCII digits — they convert directly to Myanmar
        // digits and are prepended to candidate surfaces after the
        // composable portion is parsed.
        let (digitPrefix, postDigitBuffer) = Self.splitLeadingDigits(displayBuffer)
        // Candidates are generated only from the leading run of composing
        // characters. Anything after the first non-composing character
        // (punctuation, whitespace, etc.) is held aside and emitted verbatim
        // on commit — this lets the user freely mix Burmese-convertible text
        // with literal content without the IME swallowing either.
        let (rawComposable, rawLiteralTail) = Self.splitComposablePrefix(postDigitBuffer)
        // `.` is in `Romanization.composingCharacters` for abbreviation
        // handling, so trailing punctuation lands in the composable portion
        // rather than the literal tail. When punctuation mapping is on,
        // peel those trailing mapped chars off so the parser doesn't try
        // to consume them — they rejoin the tail below and get substituted
        // with their Myanmar equivalent when the surface is assembled.
        let composable: String
        let literalTail: String
        if burmesePunctuationEnabled {
            let (kept, peeled) = Self.stripTrailingMappablePunctuation(rawComposable)
            composable = kept
            literalTail = peeled + rawLiteralTail
        } else {
            composable = rawComposable
            literalTail = rawLiteralTail
        }
        let initialNormalized = Romanization.normalize(composable)
        guard !initialNormalized.isEmpty else {
            // No composable text: if digits or literal text are present,
            // offer Burmese and Arabic digit candidates directly.
            let rawFullLiteral = digitPrefix + literalTail
            let mappedTail = burmesePunctuationEnabled
                ? Self.mapPunctuation(literalTail)
                : literalTail
            let fullLiteral = digitPrefix + mappedTail
            if Self.containsDigit(fullLiteral) {
                let burmese = Self.arabicToBurmeseDigits(fullLiteral)
                var candidates = [Candidate(
                    surface: burmese,
                    reading: rawFullLiteral,
                    source: .grammar,
                    score: 0
                )]
                // Measure-word expansions apply only when the buffer is pure
                // ASCII digits (no tail content at all). Cap to 2 suffixes per
                // buffer so the plain-digit candidate stays the default pick.
                if settings?.numberMeasureWordsEnabled == true,
                   literalTail.isEmpty,
                   !digitPrefix.isEmpty {
                    for entry in NumberMeasureWords.shared.candidates(
                        forDigits: digitPrefix, limit: 2
                    ) {
                        candidates.append(Candidate(
                            surface: "\(burmese) \(entry.measureWord)",
                            reading: rawFullLiteral,
                            source: .grammar,
                            score: 0
                        ))
                    }
                }
                if burmese != rawFullLiteral {
                    candidates.append(Candidate(
                        surface: rawFullLiteral,
                        reading: rawFullLiteral,
                        source: .grammar,
                        score: 0
                    ))
                }
                return CompositionState(
                    rawBuffer: displayBuffer,
                    selectedCandidateIndex: 0,
                    candidates: candidates,
                    committedContext: context
                )
            }
            return CompositionState(
                rawBuffer: displayBuffer,
                selectedCandidateIndex: 0,
                candidates: [],
                committedContext: context
            )
        }

        // Shrink from the right until the parser produces a fully legal
        // parse that doesn't begin with a standalone tall-aa vowel (ar2,
        // aw2, out2, aung2). The dropped suffix joins `literalTail`, so
        // "min:123" emits မင်း + "123" and "ar2" emits ာ + "2" — the
        // tall-aa variant remains reachable only when a descender onset is
        // actually present in the buffer.
        //
        // The probe always runs on the full normalized buffer: probing
        // only a trailing slice would start mid-syllable for long inputs
        // and reject valid letters that parse fine in full context.
        //
        // `parseLongestAcceptablePrefix` collapses the per-length loop
        // into a single DP pass + backward walk of its buckets. On garbage
        // / keyboard-bashing input this turns O(n) full parses into O(1).
        let (acceptableLen, _) = parser.parseLongestAcceptablePrefix(
            initialNormalized,
            maxResults: 1,
            acceptable: Self.isAcceptableParse
        )
        let initialChars = Array(initialNormalized)
        let normalized = String(initialChars.prefix(acceptableLen))
        let droppedTail = String(initialChars.suffix(initialChars.count - acceptableLen))

        guard !normalized.isEmpty else {
            return CompositionState(
                rawBuffer: displayBuffer,
                selectedCandidateIndex: 0,
                candidates: [],
                committedContext: context
            )
        }

        let rawEffectiveTail = droppedTail + literalTail
        // Punctuation auto-mapping substitutes Myanmar ။/၊ inside the tail
        // so the trailing char appears as part of each candidate surface
        // instead of forcing an early commit. Mapping touches only the
        // exact five ASCII punctuation chars — letters the parser dropped
        // into `droppedTail` pass through unchanged.
        let effectiveTail = burmesePunctuationEnabled
            ? Self.mapPunctuation(rawEffectiveTail)
            : rawEffectiveTail

        // Prefix-stability anchor: when the new buffer extends a
        // previously-rendered one *and* that anchor is mature enough
        // (`anchor.normalized.count >= anchorCommitThreshold`), reuse
        // the anchor surface verbatim and only re-parse the tail. Mature
        // anchors are treated as committed so the already-visible
        // rendering cannot drift. Below the threshold the anchor is
        // tentative — we perform a fresh full-buffer parse instead, so
        // early ambiguous picks get overwritten once evidence accrues.
        cacheLock.lock()
        let historySnapshot = anchorHistory
        cacheLock.unlock()
        // Walk the history deepest → shallowest and pick the first anchor
        // whose (a) normalized is a strict prefix of the current buffer,
        // (b) is long enough to count as committed, and (c) whose tail
        // parses on its own. A mature anchor whose tail cannot parse
        // (e.g. single trailing "a" or ":") would otherwise zero out the
        // candidate panel or force a full-buffer fallback that drifts;
        // stepping back to a shallower checkpoint gives us a parseable
        // tail while still preserving all prior committed text.
        // Minimum tail length for anchor-based windowing. A very short
        // tail (e.g. 1-2 chars) always "parses" as a bare consonant, but
        // that greedily locks in the anchor boundary and prevents multi-
        // character onsets (like "th" → သ) from forming across it. The
        // tail must be long enough for the parser to see the full onset +
        // vowel at the boundary; `maxOnsetLen` is the safe minimum.
        let minAnchorTailLen = parser.maxOnsetLen
        let priorAnchor: PrefixAnchor? = {
            for anchor in historySnapshot.reversed() {
                guard !anchor.normalized.isEmpty,
                      normalized.hasPrefix(anchor.normalized),
                      normalized.count > anchor.normalized.count,
                      anchor.normalized.count >= anchorCommitThreshold
                else { continue }
                let tail = String(normalized.suffix(normalized.count - anchor.normalized.count))
                guard tail.count >= minAnchorTailLen else { continue }
                let probe = parser.parseCandidates(tail, maxResults: 1)
                if probe.contains(where: { Self.isAcceptableParse($0) }) {
                    return anchor
                }
            }
            return nil
        }()
        // Suppress anchor-windowing when the full normalized buffer has an
        // exact-alias lexicon entry: a curated multi-word lexicon hit like
        // "မင်္ဂလာပါ" deserves to win over a synthesized prefix + tail
        // rendering. Anchor-windowing is still correct for novel inputs
        // where no full-buffer lexicon entry exists (the kwyantawkahtamin
        // case), because there the lookup is empty and this guard is false.
        let preAliasPrefix = Romanization.aliasReading(normalized)
        let preComposeKey = Romanization.composeLookupKey(normalized)
        let hasExactLexiconMatch: Bool = {
            let hits = candidateStore.lookup(prefix: preAliasPrefix, previousSurface: context.last)
            return hits.contains {
                Romanization.aliasReading($0.reading) == preAliasPrefix
                    || Romanization.composeLookupKey($0.reading) == preComposeKey
            }
        }()
        // Only use anchor-based parse splitting for long buffers where the
        // sliding window is needed. For short buffers (below compositionWindowSize),
        // always do a full-buffer parse so that syllable boundaries can be
        // freely revised as new characters arrive. Without this gate, the anchor
        // greedily commits boundaries that later keystrokes should change —
        // e.g. "la" + "r" staying as လ+ရ instead of becoming လာ (l + ar vowel),
        // or "ka" + "h" staying as က+ဟ instead of becoming က+ထ (ka + ht onset).
        let anchorApplies = priorAnchor != nil && !hasExactLexiconMatch && normalized.count > compositionWindowSize
        // Latest (deepest) anchor, regardless of tail-parseability. Used
        // during window-fallback to promote candidates that preserve the
        // full committed surface on screen.
        let latestAnchor: PrefixAnchor? = {
            for anchor in historySnapshot.reversed() {
                guard !anchor.normalized.isEmpty,
                      normalized.hasPrefix(anchor.normalized),
                      normalized.count > anchor.normalized.count,
                      anchor.normalized.count >= anchorCommitThreshold
                else { continue }
                return anchor
            }
            return nil
        }()

        let prefixBranches: [FrozenPrefixBranch]
        let parseInput: String
        let windowed: Bool
        var lmCache: [LMScoreKey: Double] = [:]
        if anchorApplies, let anchor = priorAnchor {
            let anchorLM = scoreSurfaceCached(anchor.surface, context: context, cache: &lmCache)
            prefixBranches = [FrozenPrefixBranch(
                output: anchor.surface,
                reading: anchor.reading,
                lmScore: anchorLM,
                contextWords: context + [anchor.surface]
            )]
            parseInput = String(normalized.suffix(normalized.count - anchor.normalized.count))
            windowed = true
        } else if normalized.count > compositionWindowSize {
            // Prefer reusing a previously chosen frozen prefix so the
            // "committed" portion the user sees doesn't shift as they
            // type. The cached prefix is reused verbatim when it is
            // still a prefix of the current buffer and the remaining
            // tail hasn't grown past `maxActiveTailSize`. Only when the
            // tail exceeds that budget do we extend the split forward —
            // the new split is constrained to land at or after the
            // cached endpoint, so the committed portion only grows.
            let cachedLen = stableCachedPrefixLength(for: normalized)
            let split: Int
            if let cached = cachedLen,
               normalized.count - cached <= Self.maxActiveTailSize {
                split = cached
            } else {
                split = Self.findSyllableSafeSplit(
                    in: normalized,
                    parser: parser,
                    targetTail: compositionWindowSize,
                    lowerBound: cachedLen ?? 0
                )
            }
            let frozenPrefix = String(normalized.prefix(split))
            let activeTail = String(normalized.suffix(normalized.count - split))
            prefixBranches = renderFrozenPrefixBranches(frozenPrefix, baseContext: context, lmCache: &lmCache)
            parseInput = activeTail
            windowed = true
        } else {
            prefixBranches = []
            parseInput = normalized
            windowed = false
        }

        // When windowed, the tail-only input occasionally can't parse as
        // a standalone syllable (e.g. "ka" has no onset-less "a" rule in
        // this romanization). Falling through to an empty candidate pool
        // would blank the panel mid-word. Detect that case and retry
        // with the full normalized buffer so the user still sees
        // candidates — we trade a per-keystroke re-parse of the prefix
        // for continuity of the panel.
        var effectiveParseInput = parseInput
        var effectivePrefixBranches = prefixBranches
        var effectiveWindowed = windowed
        var grammarParses = parser.parseCandidates(effectiveParseInput, maxResults: Self.grammarCandidateBudget)
        // `windowFallback` is set when the tail-only parse failed so we
        // retried with the full buffer. In that case the anchor is still
        // the authoritative rendering of the prefix — we just couldn't
        // use windowing for this keystroke. We must not overwrite the
        // anchor with the fresh fallback top (which may have picked a
        // different decomposition driven by whole-buffer LM scores).
        var windowFallback = false
        if effectiveWindowed && grammarParses.allSatisfy({ !Self.isAcceptableParse($0) }) {
            effectiveParseInput = normalized
            effectivePrefixBranches = []
            effectiveWindowed = false
            windowFallback = true
            grammarParses = parser.parseCandidates(effectiveParseInput, maxResults: Self.grammarCandidateBudget)
        }

        var grammarCandidates: [RankedGrammarCandidate]
        if effectiveWindowed {
            grammarCandidates = []
            grammarCandidates.reserveCapacity(grammarParses.count * effectivePrefixBranches.count)
            for branch in effectivePrefixBranches {
                for parse in grammarParses {
                    let surface = branch.output + parse.output
                    let reading = branch.reading + parse.reading
                    let tailLM = scoreSurfaceCached(parse.output, context: branch.contextWords, cache: &lmCache)
                    grammarCandidates.append(RankedGrammarCandidate(
                        candidate: Candidate(
                            surface: surface,
                            reading: reading,
                            source: .grammar,
                            score: Double(parse.score)
                        ),
                        legalityScore: parse.legalityScore,
                        aliasCost: parse.aliasCost,
                        parserScore: parse.score,
                        structureCost: parse.structureCost,
                        syllableCount: parse.syllableCount,
                        rarityPenalty: parse.rarityPenalty,
                        lmLogProb: branch.lmScore + tailLM
                    ))
                }
            }
        } else {
            grammarCandidates = grammarParses.map { parse in
                RankedGrammarCandidate(
                    candidate: Candidate(
                        surface: parse.output,
                        reading: parse.reading,
                        source: .grammar,
                        score: Double(parse.score)
                    ),
                    legalityScore: parse.legalityScore,
                    aliasCost: parse.aliasCost,
                    parserScore: parse.score,
                    structureCost: parse.structureCost,
                    syllableCount: parse.syllableCount,
                    rarityPenalty: parse.rarityPenalty,
                    lmLogProb: scoreSurfaceCached(parse.output, context: context, cache: &lmCache)
                )
            }
        }
        // Two branches × tail can converge on the same surface. Keep the
        // higher-LM-scored copy so dedup doesn't drop the winning branch.
        if effectiveWindowed {
            var bestBySurface: [String: Int] = [:]
            var deduped: [RankedGrammarCandidate] = []
            for candidate in grammarCandidates {
                let key = candidate.candidate.surface
                if let existing = bestBySurface[key] {
                    if candidate.lmLogProb > deduped[existing].lmLogProb {
                        deduped[existing] = candidate
                    }
                } else {
                    bestBySurface[key] = deduped.count
                    deduped.append(candidate)
                }
            }
            grammarCandidates = deduped
        }
        grammarCandidates.sort { lhs, rhs in
            grammarCandidateIsBetter(lhs, than: rhs)
        }
        grammarCandidates = pruneByLmMargin(grammarCandidates, keyPath: \.lmLogProb)
        grammarCandidates = promoteAliasAlternate(grammarCandidates)

        // Skip lexicon lookup entirely when a frozen prefix is in play:
        // multi-word lexicon hits past the window boundary aren't useful,
        // and the prefix lookup would be dominated by the cached output.
        let previousSurface = context.last
        let aliasPrefix = Romanization.aliasReading(normalized)
        let composePrefix = Romanization.composeLookupKey(normalized)
        let lexiconCandidates: [Candidate] = effectiveWindowed
            ? []
            : candidateStore.lookup(prefix: aliasPrefix, previousSurface: previousSurface)
        // History lookup uses the same alias key as the lexicon so stored
        // reads (written by `recordSelection`) line up exactly with reads.
        // Unlike lexicon candidates, history entries carry a self-contained
        // surface that isn't composed with the frozen prefix, so they are
        // safe to surface even when windowing is active — otherwise a user
        // who committed a long phrase once wouldn't see it again the next
        // time they typed the same reading (the buffer crosses the window
        // threshold long before they reach the end).
        let historyEnabled = settings?.learningEnabled ?? true
        let historyCandidates: [Candidate] = historyEnabled
            ? historyStore.lookup(prefix: aliasPrefix, previousSurface: previousSurface)
            : []
        cacheLock.lock()
        lastHistoryKey = aliasPrefix
        cacheLock.unlock()

        var grammarSurfaceIndex: [String: Int] = [:]
        for (index, candidate) in grammarCandidates.enumerated() {
            grammarSurfaceIndex[candidate.candidate.surface] = index
        }

        var uniqueLexiconCandidates: [RankedLexiconCandidate] = []
        var seenLexiconSurfaces: Set<String> = []

        for lexiconCandidate in lexiconCandidates {
            if let grammarIndex = grammarSurfaceIndex[lexiconCandidate.surface] {
                grammarCandidates[grammarIndex].candidate = Candidate(
                    surface: grammarCandidates[grammarIndex].candidate.surface,
                    reading: grammarCandidates[grammarIndex].candidate.reading,
                    source: .grammar,
                    score: grammarCandidates[grammarIndex].candidate.score + lexiconCandidate.score
                )
                continue
            }

            if seenLexiconSurfaces.insert(lexiconCandidate.surface).inserted {
                uniqueLexiconCandidates.append(
                    RankedLexiconCandidate(
                        candidate: lexiconCandidate,
                        aliasPenalty: Romanization.aliasPenaltyCount(for: lexiconCandidate.reading),
                        aliasReading: Romanization.aliasReading(lexiconCandidate.reading),
                        composeReading: Romanization.composeLookupKey(lexiconCandidate.reading),
                        lmLogProb: scoreSurfaceCached(lexiconCandidate.surface, context: context, cache: &lmCache)
                    )
                )
            }
        }

        uniqueLexiconCandidates.sort { lhs, rhs in
            lexiconCandidateIsBetter(lhs, than: rhs, aliasPrefix: aliasPrefix, composePrefix: composePrefix)
        }
        uniqueLexiconCandidates = pruneByLmMargin(uniqueLexiconCandidates, keyPath: \.lmLogProb)

        let primaryGrammar = Array(grammarCandidates.prefix(3))
        let remainingGrammar = Array(grammarCandidates.dropFirst(3))
        let exactAliasLexicon = uniqueLexiconCandidates.filter { $0.aliasReading == aliasPrefix }
        let exactComposeLexicon = uniqueLexiconCandidates.filter {
            $0.aliasReading != aliasPrefix && $0.composeReading == composePrefix
        }
        let prioritizedLexicon = Array(
            (exactAliasLexicon.isEmpty ? exactComposeLexicon : exactAliasLexicon)
                .prefix(2)
        )
        let prioritizedKeys = Set(prioritizedLexicon.map(lexiconCandidateKey))
        let trailingLexicon = uniqueLexiconCandidates.filter { !prioritizedKeys.contains(lexiconCandidateKey($0)) }

        var merged: [Candidate] = prioritizedLexicon.map(\.candidate)

        for grammarCandidate in primaryGrammar where merged.count < candidatePageSize {
            merged.append(grammarCandidate.candidate)
        }

        for lexiconCandidate in trailingLexicon where merged.count < candidatePageSize {
            merged.append(lexiconCandidate.candidate)
        }

        for grammarCandidate in remainingGrammar where merged.count < candidatePageSize {
            merged.append(grammarCandidate.candidate)
        }

        // History promotion: the user previously committed these surfaces
        // under the same alias key, so float them to the top. Walk lowest
        // score first so the highest-scoring history entry lands at index 0
        // after successive front-inserts. Surfaces already in `merged` are
        // moved; unseen surfaces are injected (the entry was legal when
        // first committed, so it's safe to resurface).
        for historyCandidate in historyCandidates.sorted(by: { $0.score < $1.score }) {
            if let existing = merged.firstIndex(where: { $0.surface == historyCandidate.surface }) {
                let keeper = merged.remove(at: existing)
                merged.insert(keeper, at: 0)
            } else {
                merged.insert(historyCandidate, at: 0)
            }
        }

        merged = Self.expandAaVariants(merged)

        // Anchor promotion: when the top candidate drifts away from a
        // previously established prefix, promote any candidate that
        // preserves the anchor surface. Walk the anchor history from
        // deepest to shallowest: intermediate anchors may have held
        // temporarily wrong syllable decompositions (e.g. "kah" → ကအ
        // before "kaht" → ကထ resolved), so skip those and find the
        // deepest anchor whose surface actually appears in a candidate.
        // Surface comparison strips ZWSPs because lexicon entries may
        // contain U+200B word-boundary markers that grammar-generated
        // surfaces lack.
        //
        // A history-sourced top outranks anchor stability: the user
        // explicitly committed that surface previously, so displacing it
        // with a parser-derived anchor extension would revert a deliberate
        // pick.
        if !merged.isEmpty, merged[0].source != .history {
            var promoted = false
            for anchor in historySnapshot.reversed() {
                guard !anchor.normalized.isEmpty,
                      normalized.hasPrefix(anchor.normalized),
                      normalized.count > anchor.normalized.count,
                      anchor.normalized.count >= anchorCommitThreshold
                else { continue }
                let anchorKey = Self.stripZWSP(anchor.surface)
                // Already matching — no promotion needed.
                if Self.scalarHasPrefix(Self.stripZWSP(merged[0].surface), anchorKey) {
                    promoted = true
                    break
                }
                if let idx = merged.firstIndex(where: { Self.scalarHasPrefix(Self.stripZWSP($0.surface), anchorKey) }) {
                    let keeper = merged.remove(at: idx)
                    merged.insert(keeper, at: 0)
                    promoted = true
                    break
                }
            }
            // No existing candidate matched any anchor. The full-buffer
            // parse has the correct syllable structure but may have
            // drifted in ya-pin/ya-yit medial choice. Check whether the
            // difference is only in medials — if so, create a variant
            // with the anchor's medial swapped in. This preserves the
            // correct syllable count while keeping the user's previously-
            // seen prefix stable on screen.
            if !promoted {
                let topStripped = Self.stripZWSP(merged[0].surface)
                for anchor in historySnapshot.reversed() {
                    guard !anchor.normalized.isEmpty,
                          normalized.hasPrefix(anchor.normalized),
                          normalized.count > anchor.normalized.count,
                          anchor.normalized.count >= anchorCommitThreshold
                    else { continue }
                    let anchorStripped = Self.stripZWSP(anchor.surface)
                    // Check if the surfaces match after normalizing
                    // ya-pin (U+103B) ↔ ya-yit (U+103C) medials.
                    let topNorm = Self.normalizeYaPinYaYit(topStripped)
                    let anchorNorm = Self.normalizeYaPinYaYit(anchorStripped)
                    if topNorm.hasPrefix(anchorNorm)
                        && !topStripped.hasPrefix(anchorStripped) {
                        let variant = Self.substituteMedials(
                            in: merged[0].surface,
                            matching: anchorStripped
                        )
                        merged.insert(Candidate(
                            surface: variant,
                            reading: merged[0].reading,
                            source: merged[0].source,
                            score: merged[0].score
                        ), at: 0)
                        break
                    }
                }
            }
        }

        // Record the new anchor for the next update. Capturing the top
        // candidate's (normalized, surface, reading) means subsequent
        // keystrokes that extend `normalized` reuse this exact rendering
        // rather than re-parsing and potentially picking a different
        // decomposition. During a window-fallback we keep the existing
        // anchor — the rendering the user still sees on screen — rather
        // than committing the fallback top that may have drifted.
        if !windowFallback {
            cacheLock.lock()
            // Skip history candidates when picking the anchor: their surface
            // is the full stored rendering for a longer reading that still
            // begins with the currently-typed prefix, so capturing it as
            // the anchor for `normalized` pairs a short key with an overly
            // long surface. A later windowed update would reuse that anchor
            // as a frozen prefix and concatenate a fresh tail parse,
            // producing candidates shaped like `<full history surface> +
            // <tail re-rendered>`. The non-history top reflects the actual
            // syllable rendering of the typed chars and is safe to anchor.
            if let top = merged.first(where: { $0.source != .history }) {
                // Prune prior entries that are stale: either (a) their
                // normalized is not a prefix of the current buffer (user
                // backspaced/diverged), or (b) their surface is not a
                // prefix of the new top's surface (an intermediate
                // decomposition that was superseded — e.g. step 11 "kah"
                // → ကအ gets pruned when step 12 "kaht" → ကထ resolves
                // differently). This prevents stale anchors from being
                // used in synthesis and producing extra syllable splits.
                let topStripped = Self.stripZWSP(top.surface)
                let topScalars = Array(topStripped.unicodeScalars)
                anchorHistory.removeAll { anchor in
                    if !normalized.hasPrefix(anchor.normalized) { return true }
                    let anchorStripped = Self.stripZWSP(anchor.surface)
                    if !Self.scalarHasPrefix(topStripped, anchorStripped) { return true }
                    // Anchor's last consonant or medial was extended by
                    // an additional sign in the new top (e.g. anchor
                    // `...ဘ` followed by a medial `ြ` in top `...ဘြ`, or
                    // anchor `...ပြ` followed by a vowel `ီ` in top
                    // `...ပြီ`). Reusing that stale anchor would prevent
                    // the extension from forming in subsequent windowing.
                    let anchorScalarCount = anchorStripped.unicodeScalars.count
                    if anchorScalarCount > 0,
                       anchorScalarCount < topScalars.count,
                       let last = anchorStripped.unicodeScalars.last,
                       Myanmar.isConsonant(last) || Myanmar.isMedial(last),
                       Self.isMedialOrMarker(topScalars[anchorScalarCount]) {
                        return true
                    }
                    return false
                }
                // Replace the last entry if it has the same normalized
                // length (we're updating the same checkpoint, not adding).
                if let last = anchorHistory.last, last.normalized == normalized {
                    anchorHistory.removeLast()
                }
                anchorHistory.append(PrefixAnchor(
                    normalized: normalized,
                    surface: top.surface,
                    reading: top.reading
                ))
                if anchorHistory.count > Self.maxAnchorHistory {
                    anchorHistory.removeFirst(anchorHistory.count - Self.maxAnchorHistory)
                }
            }
            cacheLock.unlock()
        }

        // Attach digit prefix and literal tail to each candidate surface.
        // When either contains digits, produce two variants per candidate:
        // primary with all digits as Burmese, secondary with Arabic.
        let hasDigitAffixes = Self.containsDigit(digitPrefix) || Self.containsDigit(effectiveTail)
        let mergedWithAffixes: [Candidate]
        if digitPrefix.isEmpty && effectiveTail.isEmpty {
            mergedWithAffixes = merged
        } else if hasDigitAffixes {
            let burmesePrefix = Self.arabicToBurmeseDigits(digitPrefix)
            let burmeseTail = Self.arabicToBurmeseDigits(effectiveTail)
            var expanded: [Candidate] = []
            var seen: Set<String> = []
            for candidate in merged {
                let primary = burmesePrefix + candidate.surface + burmeseTail
                if seen.insert(primary).inserted {
                    expanded.append(Candidate(
                        surface: primary,
                        reading: candidate.reading,
                        source: candidate.source,
                        score: candidate.score
                    ))
                }
                let secondary = digitPrefix + candidate.surface + effectiveTail
                if secondary != primary, seen.insert(secondary).inserted {
                    expanded.append(Candidate(
                        surface: secondary,
                        reading: candidate.reading,
                        source: candidate.source,
                        score: candidate.score
                    ))
                }
            }
            mergedWithAffixes = expanded
        } else {
            mergedWithAffixes = merged.map { candidate in
                Candidate(
                    surface: digitPrefix + candidate.surface + effectiveTail,
                    reading: candidate.reading,
                    source: candidate.source,
                    score: candidate.score
                )
            }
        }

        return CompositionState(
            rawBuffer: displayBuffer,
            selectedCandidateIndex: 0,
            candidates: mergedWithAffixes,
            committedContext: context
        )
    }

    /// Commit the currently selected candidate.
    /// Returns the committed surface text: the selected candidate for the
    /// convertible prefix, followed by any unconverted tail from the raw
    /// buffer emitted verbatim.
    public func commit(state: CompositionState) -> String {
        guard !state.candidates.isEmpty,
              state.selectedCandidateIndex < state.candidates.count else {
            return state.rawBuffer
        }
        // Candidate surfaces already include the literal tail (appended in
        // update()), so committing the selection emits both parts together.
        return state.candidates[state.selectedCandidateIndex].surface
    }

    /// Record the user's selection in the history store so it can be
    /// promoted on subsequent compositions. Writes the alias-normalized
    /// lookup key captured by the most recent `update` call — matching what
    /// `lookup` will see next time the same reading is typed. No-op when
    /// learning is disabled or the state has no active selection.
    public func recordSelection(state: CompositionState) {
        guard settings?.learningEnabled ?? true else { return }
        guard !state.candidates.isEmpty,
              state.selectedCandidateIndex < state.candidates.count else {
            return
        }
        let candidate = state.candidates[state.selectedCandidateIndex]
        // History-sourced picks must bump the existing row rather than
        // creating a new shortcut keyed on whatever prefix was typed —
        // otherwise picking a long history entry via a short prefix would
        // pollute the table with partial-key duplicates.
        let key: String
        if candidate.source == .history, !candidate.reading.isEmpty {
            key = candidate.reading
        } else {
            cacheLock.lock()
            key = lastHistoryKey
            cacheLock.unlock()
        }
        guard !key.isEmpty else { return }
        historyStore.record(reading: key, surface: candidate.surface)
    }

    /// Cancel composition: return the raw buffer unchanged.
    public func cancel(state: CompositionState) -> String {
        state.rawBuffer
    }

    /// Auto-correct the aa sign in each candidate surface to match the
    /// descender requirement of its preceding consonant: descender onsets
    /// (kha, ga, nga, da, pa, wa) take tall ါ (U+102B); others take short
    /// ာ (U+102C). Previously both shapes were emitted as siblings, which
    /// roughly doubled the candidate panel with orthographically wrong
    /// forms. Collapsing to the single correct shape removes that noise.
    private static func expandAaVariants(_ candidates: [Candidate]) -> [Candidate] {
        var result: [Candidate] = []
        var seen: Set<String> = []
        for candidate in candidates {
            let corrected = correctAaShape(candidate.surface)
            let surface = corrected == candidate.surface ? candidate.surface : corrected
            guard seen.insert(surface).inserted else { continue }
            if surface == candidate.surface {
                result.append(candidate)
            } else {
                result.append(Candidate(
                    surface: surface,
                    reading: candidate.reading,
                    source: candidate.source,
                    score: candidate.score
                ))
            }
        }
        return result
    }

    /// Walk a surface string and rewrite each ာ/ါ to the shape appropriate
    /// for its preceding consonant. Medials and signs between the
    /// consonant and the aa sign are skipped over.
    ///
    /// Operates on Unicode scalars, not grapheme clusters: Myanmar
    /// consonant + dependent vowel signs form a single extended grapheme,
    /// so a `Character`-level scan would never see the aa scalar on its
    /// own and the correction would silently no-op on multi-sign
    /// syllables like `ပေါင်း`.
    private static func correctAaShape(_ text: String) -> String {
        let shortAa: UInt32 = 0x102C
        let tallAa: UInt32 = 0x102B
        var scalars = Array(text.unicodeScalars)
        let tallAaSet: Set<UInt32> = Set(Grammar.requiresTallAa.compactMap { $0.unicodeScalars.first?.value })
        for i in 0..<scalars.count {
            let v = scalars[i].value
            guard v == shortAa || v == tallAa else { continue }
            var j = i - 1
            while j >= 0 {
                let prev = scalars[j]
                if Myanmar.isConsonant(prev) {
                    let wantsTall = tallAaSet.contains(prev.value)
                    let target: UInt32 = wantsTall ? tallAa : shortAa
                    if v != target {
                        scalars[i] = Unicode.Scalar(target)!
                    }
                    break
                }
                j -= 1
            }
        }
        var result = ""
        result.unicodeScalars.reserveCapacity(scalars.count)
        for scalar in scalars {
            result.unicodeScalars.append(scalar)
        }
        return result
    }

    /// Tall-aa vowel keys that only make sense after a descender consonant.
    /// When a parse's reading *starts* with one of these, it means the parser
    /// consumed the token as a standalone dependent vowel — which the engine
    /// rejects so the trailing "2" falls out as a literal tail instead.
    private static let standaloneTallAaReadings: [String] = [
        "ar2", "aw2", "out2", "aung2",
    ]

    /// Drop candidates whose LM log-prob trails the best by more than
    /// `lmPruneMargin`. Preserves input order (callers pre-sort), and always
    /// keeps the top candidate so the panel never ends up empty.
    private func pruneByLmMargin<T>(
        _ candidates: [T],
        keyPath: KeyPath<T, Double>
    ) -> [T] {
        guard candidates.count > 1 else { return candidates }
        var maxLm = -Double.infinity
        for c in candidates {
            let lp = c[keyPath: keyPath]
            if lp > maxLm { maxLm = lp }
        }
        guard maxLm.isFinite else { return candidates }
        let floor = maxLm - lmPruneMargin
        let filtered = candidates.filter { $0[keyPath: keyPath] >= floor }
        return filtered.isEmpty ? [candidates[0]] : filtered
    }

    /// Find a character index in `normalized` that is safe to use as the
    /// frozen-prefix / active-tail boundary. The split is "safe" when the
    /// prefix `normalized[..<split]` parses fully legally on its own —
    /// guaranteeing it ends at a syllable boundary so the tail re-parse
    /// doesn't miss letters or invent garbage parses.
    ///
    /// Starts at `normalized.count - targetTail` and scans backward up to
    /// `targetTail` characters. If no legal split is found, returns the
    /// initial target so the engine still windows (the tail will absorb
    /// any boundary artifact).
    private static func findSyllableSafeSplit(
        in normalized: String,
        parser: SyllableParser,
        targetTail: Int,
        lowerBound: Int = 0
    ) -> Int {
        let total = normalized.count
        let target = total - targetTail
        guard target > 0 else { return 0 }
        let chars = Array(normalized)
        // Never let the split regress below `lowerBound` — that keeps a
        // previously committed prefix from shrinking when we're forced
        // to recompute because the tail outgrew its budget.
        let scanFloor = max(1, lowerBound)
        // Cap the walk-back to one syllable's worth of characters. No legal
        // syllable boundary spans more than `maxOnsetLen + maxVowelLen`, so
        // if we don't find a legal prefix within that window the buffer is
        // unparseable (garbage / keyboard bashing) — walking further just
        // burns N-best parses against a string the user isn't going to
        // keep typing. Give up and return the target split unchanged.
        let maxWalkBack = parser.maxOnsetLen + parser.maxVowelLen
        let scanLimit = max(scanFloor, target - maxWalkBack)
        var split = max(target, scanFloor)
        while split >= scanLimit {
            let prefix = String(chars[0..<split])
            if let parse = parser.parseCandidates(prefix, maxResults: 1).first,
               parse.legalityScore > 0 {
                return split
            }
            split -= 1
        }
        return max(target, scanFloor)
    }

    /// Length of a previously cached frozen prefix if it still applies to
    /// `normalized` — i.e. it is still a prefix of the current buffer.
    /// Returns nil otherwise (buffer shortened or diverged).
    private func stableCachedPrefixLength(for normalized: String) -> Int? {
        cacheLock.lock()
        defer { cacheLock.unlock() }
        var best: Int? = nil
        for entry in prefixCache {
            guard !entry.input.isEmpty,
                  normalized.hasPrefix(entry.input) else { continue }
            if best == nil || entry.input.count > best! {
                best = entry.input.count
            }
        }
        return best
    }

    /// Strip zero-width spaces (U+200B) so surfaces from the lexicon
    /// (which may embed ZWSP word-boundary markers) compare equal to
    /// grammar-generated surfaces (which never contain ZWSP).
    private static func stripZWSP(_ s: String) -> String {
        if s.unicodeScalars.contains(where: { $0.value == 0x200B }) {
            return String(s.unicodeScalars.filter { $0.value != 0x200B })
        }
        return s
    }

    /// Scalar-level prefix check. Swift's `String.hasPrefix` operates on
    /// grapheme clusters, which fails for Myanmar when a syllable grows
    /// across keystrokes: the anchor's trailing consonant (e.g. `ပ`,
    /// a grapheme by itself) becomes part of a composite grapheme in
    /// the next step (e.g. `ပြ` = pa + medial ra-yit). Scalar prefix
    /// semantics correctly treat the extension as preserving the anchor.
    private static func scalarHasPrefix(_ s: String, _ prefix: String) -> Bool {
        s.unicodeScalars.starts(with: prefix.unicodeScalars)
    }

    /// True if the scalar is one that attaches to a preceding consonant
    /// (medial, dependent vowel, e-kar, asat, diacritics). Used to detect
    /// when an anchor's last bare consonant has been absorbed into a
    /// cluster by a later keystroke — such anchors are orthographically
    /// stale even though scalar prefix semantics would still accept them.
    private static func isMedialOrMarker(_ scalar: Unicode.Scalar) -> Bool {
        let v = scalar.value
        // U+1031 e-kar, U+1039 virama/asat, U+103A visible asat,
        // U+103B-U+103E medials, U+102B-U+1032 dependent vowels.
        if v == 0x1031 || v == 0x1039 || v == 0x103A { return true }
        if (0x103B...0x103E).contains(v) { return true }
        if (0x102B...0x1032).contains(v) { return true }
        return false
    }

    /// Replace both ya-pin (U+103B) and ya-yit (U+103C) with ya-pin so
    /// two surfaces that differ only in that medial choice compare equal.
    private static func normalizeYaPinYaYit(_ s: String) -> String {
        if s.unicodeScalars.contains(where: { $0.value == 0x103C }) {
            return String(s.unicodeScalars.map {
                $0.value == 0x103C ? Unicode.Scalar(0x103B)! : $0
            }.map { Character($0) })
        }
        return s
    }

    /// Copy `surface` but swap each ya-pin/ya-yit medial to match the
    /// corresponding medial in `matching` (ZWSP-stripped anchor surface).
    /// Walks both scalar arrays in lockstep; when the source has a ya-pin
    /// or ya-yit at a position where the anchor also has one, the anchor's
    /// choice wins. Stops substituting when the anchor is exhausted.
    private static func substituteMedials(in surface: String, matching anchor: String) -> String {
        var result = Array(surface.unicodeScalars)
        let anchorScalars = Array(anchor.unicodeScalars)
        var ai = 0
        for si in 0..<result.count {
            guard ai < anchorScalars.count else { break }
            let sv = result[si].value
            let av = anchorScalars[ai].value
            // Skip ZWSPs in the surface (lexicon entries may have them).
            if sv == 0x200B { continue }
            if (sv == 0x103B || sv == 0x103C) && (av == 0x103B || av == 0x103C) {
                result[si] = anchorScalars[ai]
                ai += 1
            } else if sv == av {
                ai += 1
            } else {
                break
            }
        }
        return String(String.UnicodeScalarView(result))
    }

    /// Returns true when the string contains at least one ASCII digit.
    private static func containsDigit(_ s: String) -> Bool {
        s.unicodeScalars.contains { $0.value >= 0x30 && $0.value <= 0x39 }
    }

    /// Replace mapped ASCII punctuation (`.`, `,`, `!`, `?`, `;`) with their
    /// Myanmar equivalents. Non-mapped characters pass through untouched.
    private static func mapPunctuation(_ s: String) -> String {
        guard !s.isEmpty else { return s }
        var out = ""
        out.reserveCapacity(s.count)
        for c in s {
            if let replacement = PunctuationMapper.mapped(c) {
                out += replacement
            } else {
                out.append(c)
            }
        }
        return out
    }

    private struct EmbeddedPunctSplit {
        let renderedPrefix: String
        let activeBuffer: String
    }

    /// Vowel suffixes that end in `.` (e.g. `u.`, `i.`, `an.`). When the
    /// buffer already has one of these at a candidate split position, the
    /// `.` is acting as a creaky-tone / vowel modifier in the romanization
    /// and must not be folded into the Myanmar full stop.
    private static let vowelSuffixesWithTrailingDot: [String] = {
        Romanization.vowels.compactMap { entry in
            entry.roman.hasSuffix(".") ? entry.roman : nil
        }
    }()

    private static func dotActsAsVowelModifier(prefixEndingAtDot prefix: Substring) -> Bool {
        vowelSuffixesWithTrailingDot.contains(where: { prefix.hasSuffix($0) })
    }

    /// Locate the last mapped-punct character that is followed by more
    /// content, and split `buffer` there. Purely trailing mapped-punct
    /// returns `nil` — that case is already covered by the main
    /// pipeline's `stripTrailingMappablePunctuation` path.
    private func splitAtLastEmbeddedMappedPunct(_ buffer: String) -> EmbeddedPunctSplit? {
        var boundary: String.Index? = nil
        for idx in buffer.indices.reversed() {
            guard PunctuationMapper.isMappable(buffer[idx]) else { continue }
            let after = buffer.index(after: idx)
            guard after != buffer.endIndex else { continue }
            guard buffer[after...].contains(where: { !PunctuationMapper.isMappable($0) }) else {
                continue
            }
            // `.` is overloaded: it terminates a sentence when it follows
            // arbitrary content (`thar.myat`), but it is also the creaky-
            // tone marker on vowels like `u.`, `i.`, `an.`, `aung.`. If
            // the current position closes one of those vowel suffixes, the
            // `.` is acting as a modifier and must not split the buffer —
            // otherwise `rarthiu.tu.` would freeze `rarthiu.` as a punct
            // segment and render ရာသီဦ။တု instead of ရာသီဦးတု။.
            if buffer[idx] == ".",
               Self.dotActsAsVowelModifier(prefixEndingAtDot: buffer[...idx]) {
                continue
            }
            boundary = after
            break
        }
        guard let boundary else { return nil }
        return EmbeddedPunctSplit(
            renderedPrefix: renderFrozenPunctSegments(String(buffer[..<boundary])),
            activeBuffer: String(buffer[boundary...])
        )
    }

    /// Render a buffer slice as Myanmar, splitting on mapped-punct chars
    /// and running single-best parsing on each composable run between
    /// them. Used only for the frozen prefix — lexicon + N-best are
    /// reserved for the active tail.
    private func renderFrozenPunctSegments(_ s: String) -> String {
        var out = ""
        var current = ""
        for c in s {
            if let mapped = PunctuationMapper.mapped(c) {
                // When `.` closes a creaky-tone vowel suffix (`u.`, `i.`,
                // `an.`, …) it stays attached to the current composable
                // run instead of flushing as a Myanmar full stop.
                if c == ".",
                   Self.dotActsAsVowelModifier(prefixEndingAtDot: Substring(current + ".")) {
                    current.append(".")
                    continue
                }
                if !current.isEmpty {
                    out += renderFrozenSegment(current)
                    current = ""
                }
                out += mapped
            } else {
                current.append(c)
            }
        }
        if !current.isEmpty {
            out += renderFrozenSegment(current)
        }
        return out
    }

    /// Single-best render of a punct-free segment. Digits convert to
    /// Myanmar digits up front; the remaining composable run is parsed
    /// with right-shrink to skip chars the parser can't consume.
    /// Anything beyond the composable run passes through as-is (the
    /// caller has already stripped mapped-punct from the input).
    private func renderFrozenSegment(_ segment: String) -> String {
        let (digits, rest) = Self.splitLeadingDigits(segment)
        let digitPart = Self.arabicToBurmeseDigits(digits)
        let (composable, literal) = Self.splitComposablePrefix(rest)
        let normalized = Romanization.normalize(composable)
        guard !normalized.isEmpty else {
            return digitPart + composable + literal
        }
        var probe = normalized
        var dropped = ""
        while !probe.isEmpty {
            let parses = parser.parseCandidates(probe, maxResults: 1)
            if parses.contains(where: { Self.isAcceptableParse($0) }) { break }
            dropped = String(probe.removeLast()) + dropped
        }
        guard !probe.isEmpty else {
            return digitPart + composable + literal
        }
        let output = parser.parseCandidates(probe, maxResults: 1).first?.output ?? probe
        return digitPart + output + dropped + literal
    }

    /// Strip trailing mapped-punctuation characters (`.`, `,`, `!`, `?`, `;`)
    /// from the end of `s`. Returns the kept prefix and the peeled suffix
    /// in original order. Used to rescue trailing `.` from the composable
    /// buffer (it's in `Romanization.composingCharacters`) so it can be
    /// routed through the literal-tail mapping path.
    private static func stripTrailingMappablePunctuation(_ s: String) -> (kept: String, stripped: String) {
        var kept = s
        var stripped = ""
        while let last = kept.last, PunctuationMapper.isMappable(last) {
            stripped = String(last) + stripped
            kept.removeLast()
        }
        if !kept.isEmpty, stripped.first == "." {
            kept.append(".")
            stripped.removeFirst()
        }
        return (kept, stripped)
    }

    /// Replace ASCII digits (0-9) with Myanmar digits (U+1040–U+1049),
    /// leaving all other characters unchanged.
    private static func arabicToBurmeseDigits(_ s: String) -> String {
        String(s.unicodeScalars.map { scalar in
            if scalar.value >= 0x30 && scalar.value <= 0x39 {
                return Character(Unicode.Scalar(0x1040 + (scalar.value - 0x30))!)
            }
            return Character(scalar)
        })
    }

    /// Split a leading run of ASCII digits from the rest of the buffer.
    private static func splitLeadingDigits(_ buffer: String) -> (digits: String, remainder: String) {
        if let firstNonDigit = buffer.firstIndex(where: {
            guard let scalar = $0.unicodeScalars.first, $0.unicodeScalars.count == 1 else { return true }
            return scalar.value < 0x30 || scalar.value > 0x39
        }) {
            return (String(buffer[..<firstNonDigit]), String(buffer[firstNonDigit...]))
        }
        return (buffer, "")
    }

    private static func isAcceptableParse(_ parse: SyllableParse) -> Bool {
        guard parse.legalityScore > 0 else { return false }
        for reading in standaloneTallAaReadings where parse.reading.hasPrefix(reading) {
            return false
        }
        return true
    }

    /// Split a buffer into its leading run of composing characters and the
    /// remainder (starting at the first non-composing character). The
    /// composing prefix is what gets parsed into Burmese candidates; the
    /// remainder is preserved as literal text during commit.
    private static func splitComposablePrefix(_ buffer: String) -> (composable: String, literal: String) {
        let composingSet = Romanization.composingCharacters
        if let firstNonComposing = buffer.firstIndex(where: { !composingSet.contains($0) }) {
            return (String(buffer[..<firstNonComposing]), String(buffer[firstNonComposing...]))
        }
        return (buffer, "")
    }

    private func grammarCandidateIsBetter(_ lhs: RankedGrammarCandidate, than rhs: RankedGrammarCandidate) -> Bool {
        // Legality is a hard filter — orthographically legal syllables
        // always beat illegal ones.
        let lhsLegal = lhs.legalityScore > 0
        let rhsLegal = rhs.legalityScore > 0
        if lhsLegal != rhsLegal {
            return lhsLegal
        }
        // Character-class rarity sits above `syllableCount` so a longer
        // common-consonant parse outranks a shorter retroflex one when
        // the user did not type the "2" disambiguator. Rare parses stay
        // in the panel — they just aren't top-1.
        if lhs.rarityPenalty != rhs.rarityPenalty {
            return lhs.rarityPenalty < rhs.rarityPenalty
        }
        // Prefer fewer syllables before legality magnitude: when the
        // parser's min+1 widening admits extended parses, the per-syllable
        // sum in `legalityScore` mechanically favors the longer parse
        // even though the canonical (min-tier) parse is what the user
        // expects as top-1. Anchor stability depends on this.
        if lhs.syllableCount != rhs.syllableCount {
            return lhs.syllableCount < rhs.syllableCount
        }
        if lhs.legalityScore != rhs.legalityScore {
            return lhs.legalityScore > rhs.legalityScore
        }
        // LM log-prob is the primary signal (per migration plan). This
        // lets common words like ကျွန်တော် outrank parses with rare
        // consonants (ဈ, ဋ, …) that happen to share the same structural
        // alias cost. Differences smaller than a nat are treated as ties
        // so floating-point jitter doesn't flip the order.
        if abs(lhs.lmLogProb - rhs.lmLogProb) > 1.0 {
            return lhs.lmLogProb > rhs.lmLogProb
        }
        // Structural tiebreakers when the LM says the candidates are
        // roughly equally plausible: prefer fewer alias substitutions,
        // then the parser's own score, then a simpler medial structure.
        if lhs.aliasCost != rhs.aliasCost {
            return lhs.aliasCost < rhs.aliasCost
        }
        if lhs.parserScore != rhs.parserScore {
            return lhs.parserScore > rhs.parserScore
        }
        if lhs.structureCost != rhs.structureCost {
            return lhs.structureCost < rhs.structureCost
        }
        if lhs.candidate.score != rhs.candidate.score {
            return lhs.candidate.score > rhs.candidate.score
        }
        if lhs.candidate.surface != rhs.candidate.surface {
            return lhs.candidate.surface < rhs.candidate.surface
        }
        return lhs.candidate.reading < rhs.candidate.reading
    }

    private func lexiconCandidateIsBetter(
        _ lhs: RankedLexiconCandidate,
        than rhs: RankedLexiconCandidate,
        aliasPrefix: String,
        composePrefix: String
    ) -> Bool {
        let lhsMatch = lexiconMatchQuality(lhs, aliasPrefix: aliasPrefix, composePrefix: composePrefix)
        let rhsMatch = lexiconMatchQuality(rhs, aliasPrefix: aliasPrefix, composePrefix: composePrefix)
        if lhsMatch != rhsMatch {
            return lhsMatch > rhsMatch
        }
        // LM log-prob is the primary signal within a match-quality tier;
        // aliasPenalty drops to a tiebreaker. See grammarCandidateIsBetter
        // for the same reasoning.
        if abs(lhs.lmLogProb - rhs.lmLogProb) > 1.0 {
            return lhs.lmLogProb > rhs.lmLogProb
        }
        if lhs.aliasPenalty != rhs.aliasPenalty {
            return lhs.aliasPenalty < rhs.aliasPenalty
        }
        if lhs.candidate.score != rhs.candidate.score {
            return lhs.candidate.score > rhs.candidate.score
        }
        if lhs.candidate.surface != rhs.candidate.surface {
            return lhs.candidate.surface < rhs.candidate.surface
        }
        return lhs.candidate.reading < rhs.candidate.reading
    }

    private func lexiconMatchQuality(
        _ candidate: RankedLexiconCandidate,
        aliasPrefix: String,
        composePrefix: String
    ) -> Int {
        if candidate.aliasReading == aliasPrefix {
            return 2
        }
        if candidate.composeReading == composePrefix {
            return 1
        }
        return 0
    }

    private func lexiconCandidateKey(_ candidate: RankedLexiconCandidate) -> String {
        "\(candidate.candidate.surface)\u{0}\(candidate.candidate.reading)"
    }

    private func promoteAliasAlternate(_ candidates: [RankedGrammarCandidate]) -> [RankedGrammarCandidate] {
        guard candidates.count > 2 else { return candidates }

        let topReading = candidates[0].candidate.reading

        // Among alias candidates ranked beyond position 2, prefer the one
        // whose reading shares the longest common prefix with the top
        // candidate. This selects the terminal-syllable alternate (e.g.
        // "par2" over "lar2") which is what the user most likely wants.
        var bestIndex: Int?
        var bestPrefixLen = -1
        for i in 2..<candidates.count where candidates[i].aliasCost > 0 {
            let reading = candidates[i].candidate.reading
            let commonLen = topReading.commonPrefix(with: reading).count
            if commonLen > bestPrefixLen {
                bestPrefixLen = commonLen
                bestIndex = i
            }
        }

        guard let aliasIndex = bestIndex, aliasIndex > 2 else {
            return candidates
        }

        var reordered = candidates
        let aliasCandidate = reordered.remove(at: aliasIndex)
        reordered.insert(aliasCandidate, at: min(2, reordered.count))
        return reordered
    }
}
